src/app/app.module.ts, src/app/indexedDB/dbConfig.ts, src/app/models/idb.ts, src/app/utility/calanderization/calanderization.component.ts, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/utility/energy-consumption/energy-source/edit-meter-form/fuelOptions.ts, src/app/utility/energy-consumption/utility-meter-data/import-meter-data/import-meter-data.component.html, src/app/utility/energy-consumption/utility-meter-data/import-meter-data/import-meter-data.component.ts, src/app/utility/meter-grouping/energy-unit-dropdown/energy-unit-dropdown.component.html, src/app/utility/meter-grouping/energy-unit-dropdown/energy-unit-dropdown.component.spec.ts, src/app/utility/meter-grouping/energy-unit-dropdown/energy-unit-dropdown.component.ts, src/app/utility/meter-grouping/meter-grouping.component.html, src/app/utility/meter-grouping/meter-grouping.component.ts
fixes importing meter data.
(includes changes from issue 23 and 38, those PR's should be merged first)
=> Import meter data

src/app/utility/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html, src/app/utility/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/predictor-data/edit-predictor-entry-row/edit-predictor-entry-row.component.html, src/styles.css
=> Bootstrap all inputs with units

src/app/utility/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html, src/app/utility/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/utility/predictor-data/edit-predictor-entry-row/edit-predictor-entry-row.component.html, src/app/utility/predictor-data/edit-predictors/edit-predictors.component.css, src/app/utility/predictor-data/edit-predictors/edit-predictors.component.html, src/app/utility/predictor-data/predictor-data.component.html, src/styles.css
=> Updated edit form styles and windows

src/app/account-management/account/account.component.css, src/app/account-management/account/account.component.html, src/app/account-management/account/account.component.ts, src/app/dashboard/account-overview/account-utility-energy-use-table/account-utility-energy-use-table.component.html, src/app/dashboard/account-overview/facilities-table/facilities-table.component.html, src/app/dashboard/account-overview/facilities-table/facilities-table.component.ts, src/app/dashboard/facility-overview/meters-table/meters-table.component.html, src/app/dashboard/facility-overview/utility-energy-use-table/utility-energy-use-table.component.html, src/app/utility/calanderization/calanderization.component.html, src/app/utility/energy-consumption/energy-source/energy-source.component.html, src/app/utility/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/utility/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/utility/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/utility/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/predictor-data/predictor-data.component.css, src/app/utility/predictor-data/predictor-data.component.html, src/styles.css
=> Adding Responsive Table Design

src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.ts
fixes data tables subscription
=> fix utility bill tables updating

src/app/account-management/account/account.component.html, src/app/account-management/account/account.component.ts, src/app/shared/header/header.component.css, src/app/shared/header/header.component.html, src/app/shared/header/header.component.ts
=> Minor menu updates

src/app/dashboard/account-overview/account-utility-energy-use-table/account-utility-energy-use-table.component.ts, src/app/dashboard/account-overview/energy-use-donut/energy-use-donut.component.ts, src/app/dashboard/account-overview/energy-use-heat-map/energy-use-heat-map.component.ts, src/app/dashboard/account-overview/energy-use-stacked-bar-chart/energy-use-stacked-bar-chart.component.ts, src/app/dashboard/account-overview/facilities-table/facilities-table.component.ts, src/app/dashboard/dashboard.service.ts, src/app/dashboard/facility-overview/facility-bar-chart/facility-bar-chart.component.ts, src/app/indexedDB/facility-db.service.ts
connects #65 
adds support for switching between accounts and for accounts/facilities without data.
=> support switching between account in dashboard

src/app/indexedDB/utilityMeterGroup-db.service.ts, src/app/models/idb.ts, src/app/utility/meter-grouping/meter-grouping.component.css, src/app/utility/meter-grouping/meter-grouping.component.html, src/app/utility/meter-grouping/meter-grouping.component.ts, src/styles.css
=> Adding toggle to groups & updated buttons

src/app/indexedDB/utilityMeter-db.service.ts, src/app/models/idb.ts, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.ts, src/styles.css
=> Adding toggle to meters

src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/utility/energy-consumption/energy-source/energy-source.component.html, src/app/utility/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/styles.css
=> Updated form HTML

src/app/dashboard/dashboard.component.css, src/app/dashboard/dashboard.component.html, src/app/dashboard/dashboard.component.ts, src/styles.css
=> Updating Dashboard banner

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/dashboard/dashboard.component.css, src/app/page-not-found/page-not-found.component.css, src/app/page-not-found/page-not-found.component.html, src/app/page-not-found/page-not-found.component.spec.ts, src/app/page-not-found/page-not-found.component.ts, src/styles.css
=> Adding 404 Page

src/app/indexedDB/utilityMeterData-db.service.ts, src/app/models/idb.ts, src/app/utility/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.ts, src/app/utility/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/utility/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.ts, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.service.ts
=> update validation and units for meter data forms

src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.ts
=> add modal for bulk delete

src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts
=> disable meter form fields when data exists

src/app/dashboard/account-overview/facilities-table/facilities-table.component.ts, src/app/dashboard/dashboard.service.ts, src/app/dashboard/facility-overview/utility-energy-use-table/utility-energy-use-table.component.ts, src/app/shared/helper-services/calanderization.service.ts
connects #150 
fixes bug on dashboard pages relating to not enough meter data for calanderization.
=> fix bug for calanderizing not enough data entries

src/app/dashboard/empty-state/empty-state.component.ts, src/app/indexedDB/account-db.service.ts, src/app/indexedDB/facility-db.service.ts
connects #158 
async loading of test data.
using id from account in db. (just in case somehow the test accounts/facilities are not the first items in the db)
=> fixes to test data so proper ids are set and correct facility selected

src/app/app.component.html, src/app/dashboard/dashboard.component.html, src/app/dashboard/dashboard.component.ts, src/app/shared/toast-notifications/toast-notifications.component.html, src/app/shared/toast-notifications/toast-notifications.component.ts, src/app/shared/toast-notifications/toast-notifications.service.spec.ts, src/app/shared/toast-notifications/toast-notifications.service.ts
connects #124 
moves toast notification to app component.
Can just show/hide through service, similar to loading message.
Still have test in dashboard, will remove once we are using the notification in other places.
=> Issue 124 mark

src/app/shared/header/header.component.html, src/app/shared/header/header.component.ts
I am only changing the text, not actually switching the facility.
=> Switch text when on account mgnt pg

src/app/utility/energy-consumption/energy-source/energy-source.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/upload-data/upload-data.component.html
=> change button labels to Import Data

src/app/utility/energy-consumption/energy-consumption.component.html, src/app/utility/energy-consumption/energy-consumption.component.ts, src/app/utility/utility.component.css, src/app/utility/utility.component.html, src/app/utility/utility.component.ts, src/styles.css
I left these comments in because I'm not sure if I want to add it or not. Going to see what everyone thinks after they use it.
<span [hidden]="hasElectricityData">*</span>
=> Restricting Utility Navigation

src/app/utility/calanderization/calanderization-chart/calanderization-chart.component.ts, src/app/utility/calanderization/calanderization-filter/calanderization-filter.component.html, src/app/utility/calanderization/calanderization.component.css, src/app/utility/calanderization/calanderization.component.html, src/app/utility/energy-consumption/energy-source/energy-source.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/meter-grouping/meter-grouping.component.css, src/app/utility/predictor-data/predictor-data.component.html, src/app/utility/utility.component.html, src/styles.css
Connects #187 
Updated calendar graph buttons as well as the rest of the buttons for the "utility" section.
=> Utility Button Updates

src/app/account-management/facility/facility.component.html, src/app/account-management/facility/facility.component.ts, src/app/shared/import-backup-modal/import-backup-modal.component.html, src/app/shared/import-backup-modal/import-backup-modal.component.ts
=> add import to facility management page

src/app/utility/upload-data/import-meter-data-wizard/import-meter-data-wizard.component.html, src/app/utility/upload-data/upload-data.component.html
=> unhide cancel on meter number import page, fix scrolling

src/app/shared/convert-units/definitions/mass.ts
=> add Ton display unit

src/app/utility/energy-consumption/energy-source/energy-source.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/meter-grouping/meter-grouping.component.html, src/app/utility/predictor-data/predictor-data.component.html
=> add cancel button to table management modals

src/app/shared/helper-services/calanderization.service.ts
=> fix calanderized meter data bug from extra days added to days between

src/app/dashboard/dashboard.service.ts, src/app/shared/helper-services/calanderization.service.ts
connects #100 
takes into account previous year bill from all meters
=> fix previous year calculation

src/app/utility/meter-grouping/meter-grouping.component.css, src/app/utility/meter-grouping/meter-grouping.component.ts
=> fix removing all meters from groups bug

angular.json, package.json, src/app/shared/footer/footer.component.html, src/app/shared/footer/footer.component.ts, src/app/shared/sidebar/sidebar.component.html, src/app/shared/sidebar/sidebar.component.ts, src/app/utility/calanderization/calanderization-filter/calanderization-filter.component.html, src/app/utility/calanderization/calanderization-filter/calanderization-filter.component.ts
use `npm run build-prod` for production builds
small additions for production build, 
hides style guide and delete database button for production builds
=> updates for production build

src/app/utility/upload-data/import-meter-data-wizard/import-meter-data-wizard.component.ts
=> navigate off page on submit

src/app/models/calanderization.ts, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/visualization.service.ts, src/app/utility/calanderization/calanderization.component.html
=> update energy use vs consumption

src/app/utility/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts
=> fix energy unit label with consumption

src/app/shared/header/header.component.html, src/app/shared/header/header.component.ts
=> Updating header when viewing account related pages

src/app/shared/setup-progress/setup-progress.component.css, src/app/shared/setup-progress/setup-progress.component.html, src/app/shared/setup-progress/setup-progress.component.ts
=> Minimize setup wizard

src/app/shared/header/header.component.html, src/app/shared/header/header.component.ts, src/app/shared/setup-progress/setup-progress.component.css, src/app/shared/setup-progress/setup-progress.component.html, src/app/shared/setup-progress/setup-progress.component.ts, src/app/utility/upload-data/import-predictors-table/import-predictors-table.component.html
=> Issue 237 - Adding Import button under Switch Account

src/app/shared/convert-units/definitions/volume.ts, src/app/shared/helper-services/energy-units-helper.service.ts, src/app/shared/unitOptions.ts
=> added CCF to unit conversion and expanded dropdown for all utilities

src/app/shared/setup-progress/setup-progress.component.css, src/app/shared/setup-progress/setup-progress.component.html, src/app/shared/setup-progress/setup-progress.component.ts, src/styles/styles.css
=> fix canvas element

src/app/utility/help-panel/help-panel.component.html, src/app/utility/help-panel/help-panel.component.ts
=> hide site to source option in energy consumption pages

src/app/utility/visualization/correlation-plot/correlation-plot.component.ts, src/app/utility/visualization/visualization.component.ts
=> fix visualization bug

src/app/utility/calanderization/calanderization.component.css, src/app/utility/calanderization/calanderization.component.html, src/app/utility/calanderization/data-application-menu/data-application-menu.component.css, src/app/utility/calanderization/data-application-menu/data-application-menu.component.html, src/app/utility/calanderization/data-application-menu/data-application-menu.component.ts
=> responsiveness fixes and verification changes

package.json, src/app/shared/helper-services/energy-use-calculations.service.ts, src/environments/environment.prod.ts
connects #337 
fixes global variables months for production build
=> Release fixes

src/app/app.component.ts, src/index.html
=> Adding Google Analytics

src/app/account-management/sustainability-questions-form/sustainability-questions-form.component.html, src/app/account-management/sustainability-questions-form/sustainability-questions-form.component.ts, src/app/account-management/sustainability-questions-form/year-options.pipe.spec.ts, src/app/account-management/sustainability-questions-form/year-options.pipe.ts, src/app/app.module.ts
connects #365 
prevents target year from being less then baseline year
=> update logic for setting target/baseline goal years

angular.json, src/app/account-management/backup-data.service.ts, src/app/indexedDB/account-db.service.ts, src/app/indexedDB/facility-db.service.ts, src/app/indexedDB/predictors-db.service.ts
fixes import bugs from updating indexedDb api version
fixes development environment for angular version updates
=> fixes for dev bugs from angular update

main.js
connects #293 
you can open dev tools in electron window with ctrl+i or cmd+i
=> add ability to open dev tools in electron version

src/app/app.module.ts, src/app/dashboard/account-overview/account-utility-energy-use-table/account-utility-energy-use-table.component.html, src/app/dashboard/account-overview/facilities-table/facilities-table.component.html, src/app/dashboard/facility-overview/meters-table/meters-table.component.html, src/app/dashboard/facility-overview/utility-energy-use-table/utility-energy-use-table.component.html, src/app/shared/helper-pipes/custom-number.pipe.spec.ts, src/app/shared/helper-pipes/custom-number.pipe.ts, src/app/utility/calanderization/calanderization.component.html, src/app/utility/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/utility/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/utility/meter-grouping/meter-grouping.component.html, src/app/utility/predictor-data/predictor-data.component.html
connects #342 
if display value is < 10000 then rounds to max 5 sig figs
if display value is > 10000 then removes decimals
=> add custom numbers pipe for formatting display numbers

src/app/shared/helper-services/energy-use-calculations.service.ts, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/utility/upload-data/import-meter.service.ts
connects #378 
connects #264 
sets the heating capacity and emissions output rate for importing meters
=> Import updates

src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts
energyUnit sets when meter changes in import wizard.
needs verification review.
connects #264
=> issue #264

src/app/indexedDB/utilityMeterData-db.service.ts, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.ts
connects #391
do not apply site to source for raw meter readings
=> issue #391

src/app/electron/electron.service.ts, src/app/indexedDB/account-db.service.ts, src/app/shared/toast-notifications/toast-notifications.component.ts, src/app/shared/toast-notifications/toast-notifications.service.ts
connects #370 
adds disabling web disclaimer
updates local storage check for selected account
=> issue #370

src/app/shared/helper-services/energy-units-helper.service.ts, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts, src/app/utility/energy-consumption/energy-source/edit-meter/edit-meter.component.html, src/app/utility/energy-consumption/energy-source/edit-meter/edit-meter.component.ts, src/app/utility/energy-consumption/energy-source/energy-source.component.ts
connects #112 
connects #388 
adds dropdown for meter energy unit, displays when consumption unit isn't energy
=> issue #112

src/app/electron/electron.service.ts
connects #346 
updates web disclaimer to say "DOE does not have access to your data"
=> issue #346

src/app/utility/calanderization/calanderization-chart/calanderization-chart.component.ts
connects #309 
set y ticks to have same number of ticks for calanderization
=> issue #309

src/app/utility/upload-data/excel-wizard/columns-wizard/columns-wizard.component.html
connects #302 
update import help text (from review)
=> issue #302 (needs review)

src/app/dashboard/empty-state/empty-state.component.html, src/app/dashboard/empty-state/empty-state.component.ts, src/app/shared/setup-progress/setup-progress.component.html
=> fix broken link in dashboard

src/app/shared/helper-services/calanderization.service.ts, src/app/utility/calanderization/calanderization.component.html, src/app/utility/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/utility/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html
=> fix calanderization algorithm for december months

src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/energy-use-calculations.service.ts, src/app/utility/calanderization/data-application-menu/data-application-menu.component.ts, src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.service.ts
=> convert emissions correctly

src/app/utility/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/utility/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/utility/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/styles/popupsWindows.css
=> updated styling for pop up windows for meter and meter data

src/app/shared/helper-services/calanderization.service.ts
=> convert for electricity emissions

src/app/shared/example-data/Better_Plants_Partner_Backup_4-20-2021.ts
=> fix emissions in example

src/app/analysis/calculations/energy-intensity.service.ts, src/app/analysis/run-analysis/facility-analysis/facility-analysis-graph/facility-analysis-graph.component.ts, src/app/analysis/run-analysis/facility-analysis/facility-analysis-table/facility-analysis-table.component.css, src/app/analysis/run-analysis/facility-analysis/facility-analysis-table/facility-analysis-table.component.html, src/app/analysis/run-analysis/facility-analysis/facility-analysis-table/facility-analysis-table.component.ts, src/app/analysis/run-analysis/facility-analysis/facility-analysis.component.html, src/app/analysis/run-analysis/facility-analysis/facility-analysis.component.ts, src/app/indexedDB/analysis-db.service.ts, src/app/models/analysis.ts
connects #466 
breaks up facility summary table for groups and total
updates graph
=> update facility summary graph and table

src/app/account-management/account/account.component.css, src/app/account-management/account/account.component.html, src/app/account-management/facility/facility.component.css, src/app/account-management/facility/facility.component.html, src/app/analysis/analysis-banner/analysis-banner.component.css, src/app/analysis/analysis.component.html, src/app/core-components/header/header.component.html, src/app/overview-report/overview-report-banner/overview-report-banner.component.css, src/app/overview-report/overview-report.component.html, src/app/utility-data/utility-banner/utility-banner.component.css, src/app/utility-data/utility-data.component.html, src/styles/banners.css, src/styles/buttons.css, src/styles/contentContainers.css, src/styles/typography.css
=> banner headers and button colors matching for each module

src/app/help-panel/help-page/help-page.component.html, src/app/help-panel/help-page/help-page.component.spec.ts, src/app/help-panel/help-page/help-page.component.ts, src/app/help-panel/help-panel.component.html, src/app/help-panel/help-panel.component.ts, src/app/help-panel/help-panel.module.ts, src/app/static-content/help/help.component.css, src/app/static-content/help/help.component.html, src/app/static-content/help/help.component.ts
=> update help page

src/app/account/account-banner/account-banner.component.html, src/app/facility/analysis/analysis-banner/analysis-banner.component.css, src/app/facility/analysis/run-analysis/facility-analysis/facility-analysis.component.css, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.css, src/app/facility/utility-data/energy-consumption/energy-consumption.component.css, src/app/facility/utility-data/utility-banner/utility-banner.component.css
=> update tabs colors

src/app/account/overview-report/overview-report-menu/manage-report-templates/manage-report-templates.component.html, src/app/account/overview-report/overview-report-menu/overview-report-menu.component.ts
connects #456 
fixes broken navigation on update
fixes fontawesome trashcan
=> fixes to report from feedback

src/app/account/account.component.css, src/app/account/account.component.html
connects #424 
need to show all content for printing
=> fix rollup printing

src/app/facility/utility-data/upload-data/import-meter.service.ts
=> fix import set heat capacity bug

src/app/facility/analysis/calculations/analysis-calculations.service.ts
=> enforce modeled energy non negative

src/app/app-routing.module.ts, src/app/facility/utility-data/calanderization/calanderization.component.css, src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/calanderization/calanderization.component.ts, src/app/facility/utility-data/calanderization/calanderization.module.ts, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.css, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.spec.ts, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.ts, src/app/facility/utility-data/energy-consumption/energy-consumption.component.html, src/app/facility/utility-data/energy-consumption/energy-consumption.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/energy-source.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.component.ts, src/app/shared/helper-services/calanderization.service.ts
connects #546 
updates meters and calendarization pages to use tabs for each meter
TODO: add back in validation for meter table readings
=> Add Meter and Calendarization Tabs

package.json
=> change app ID to gov.ornl.amo

src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.html, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.ts, src/app/account/overview-report/better-plants-report-menu/better-plants-report-menu.component.ts, src/app/account/overview-report/overview-report-dashboard/overview-report-dashboard.component.html, src/app/account/overview-report/overview-report-dashboard/overview-report-dashboard.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.html, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.ts
=> add create copy to analysis and reports

README.md
=> updated README build instructions

src/app/shared/settings-forms/default-units-form/default-units-form.component.ts, src/app/shared/settings-forms/settings-forms.service.ts
=> fix US Average emissions dropdown bug

angular.json, package-lock.json, package.json, src/app/app.module.ts, src/app/facility/utility-data/upload-data/upload-data.component.ts, src/app/facility/utility-data/utility-banner/utility-banner.component.html, src/app/facility/utility-data/utility-banner/utility-banner.component.ts, src/app/shared/helper-services/export-to-excel-template.service.spec.ts, src/app/shared/helper-services/export-to-excel-template.service.ts, src/styles/buttons.css, tsconfig.app.json
connects #353 
adds ability to export entered facility date to an excel file in the same format as the template but without the linked dropdowns
=> Export facility data to excel "template"

src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/models/analysis.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> Add notes column for model selection

src/app/account/overview-report/basic-report/facility-report/facility-report.component.html
=> fix printing report bug splitting graph

src/app/facility/analysis/analysis.service.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.css, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.ts, src/app/indexedDB/predictors-db.service.ts, src/app/indexedDB/utilityMeterData-db.service.ts, src/app/models/idb.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
connects #620 
adds warning when model has been generated prior to new data entries
adds error if no valid models
=> add warnings for model selection and data changes

src/app/app.component.css
=> fix horizontal scrolling

src/app/facility/utility-data/predictor-data/edit-predictor-entry-row/edit-predictor-entry-row.component.ts
=> fix predictor date selection bug

src/app/facility/analysis/analysis.module.ts, src/app/facility/analysis/analysis.service.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.css, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.spec.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.ts, src/styles/sliderToggle.css
connects #621 
Moves all regression modeling UI/UX to own tab
Adds steps for setup
Enhances regression modeling UI/UX with warnings and errors
=> Updates to group analysis UI flow

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/indexedDB/predictors-db.service.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
connects #629 
connects #618 
enforce predictor selected prior to modeling
date fix for manual predictor entries
=> validation prior to modeling and predictors fix

package.json
=> update version to v0.5.0-alpha

src/app/facility/utility-data/energy-consumption/energy-consumption.component.html, src/app/facility/utility-data/utility-banner/utility-banner.component.html
=> rename utility data tabs

angular.json, package-lock.json, package.json, src/app/facility/visualization/correlation-heatmap/correlation-heatmap.component.ts, src/app/facility/visualization/correlation-plot/correlation-plot.component.ts, src/app/models/visualization.ts, src/app/shared/helper-services/visualization.service.ts
connects #305 
connects #512 
fix R2 variance and P Value
=> update visualization graphs with JStat

src/app/facility/utility-data/calanderization/calanderization.component.ts, src/app/shared/helper-services/calanderization.service.ts
=> fix calanderization filter bug

src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.css, src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.html, src/app/account/account-analysis/account-analysis-results/account-analysis-results.component.css, src/app/account/account-analysis/account-analysis-results/account-analysis-results.component.html, src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.css, src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.html, src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.ts, src/app/core-components/sidebar/sidebar.component.html, src/app/facility/analysis/analysis-banner/analysis-banner.component.css, src/app/facility/analysis/analysis-banner/analysis-banner.component.html, src/app/facility/analysis/run-analysis/facility-analysis/facility-analysis.component.css, src/app/facility/analysis/run-analysis/facility-analysis/facility-analysis.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.css, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.html, src/app/facility/facility-banner/facility-banner.component.html, src/app/facility/utility-data/calanderization/calanderization.component.css, src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/energy-consumption/energy-consumption.component.css, src/app/facility/utility-data/energy-consumption/energy-consumption.component.html, src/app/facility/utility-data/utility-banner/utility-banner.component.css, src/app/facility/utility-data/utility-banner/utility-banner.component.html
=> Add Icons to Subtabs

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/models/analysis.ts, src/app/shared/helper-services/visualization.service.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> Fixes for jstat modeling and graphing when gaps in data time

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts, src/app/indexedDB/utilityMeter-db.service.ts, src/app/models/idb.ts, src/app/shared/meterOptions.ts
connects #663 
connects #645 
fixed site to source default for new electricity meters
adds scope to meters form and object
=> add scope dropdown option to meters form

src/app/help-panel/utility/calanderization-help/calanderization-help.component.html
=> #440 help text panel calendarization

src/app/help-panel/help-panel.component.css
=> Help text scrolling #675

src/app/app.component.html, src/styles/tables.css
connects #674 
As discussed offline, including Firefox's lack of custom scrollbar color in this issue, for brevity.
=> Main panel exceeds screen height #674

src/app/account/overview-report/better-plants-report-menu/better-plants-report-menu.component.html, src/app/account/overview-report/overview-report.module.ts, src/app/shared/label-with-tooltip/label-with-tooltip.component.html, src/app/shared/label-with-tooltip/label-with-tooltip.component.ts, src/app/shared/label-with-tooltip/labelTooltips.ts, src/styles/typography.css
=> Help Text Tooltips Better Plants Report Setup #608

src/app/facility/facility-home/meter-card/meter-card.component.css, src/app/facility/facility-home/meter-card/meter-card.component.html, src/app/facility/utility-data/energy-consumption/energy-source/utility-meters-table/utility-meters-table.component.html, src/app/shared/helper-pipes/agreement-type-label.pipe.spec.ts, src/app/shared/helper-pipes/agreement-type-label.pipe.ts, src/app/shared/helper-pipes/helper-pipes.module.ts, src/app/shared/helper-pipes/scope-label.pipe.spec.ts, src/app/shared/helper-pipes/scope-label.pipe.ts
=> added pipes for scope and agreement type display

src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.html, src/app/account/overview-report/overview-report-dashboard/overview-report-dashboard.component.html, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.html, src/app/facility/utility-data/energy-consumption/energy-source/utility-meters-table/utility-meters-table.component.html
connects #644 
edit, copy, delete
=> Update action buttons order

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts, src/app/facility/utility-data/upload-data/import-meter.service.ts, src/app/models/idb.ts, src/app/shared/example-data/Better_Plants_Example.ts, src/app/shared/helper-services/convert-meter-data.service.ts
=> only show "Site to Source" if "Include in Energy" is selected

src/index.html
=> update VERIFI title

src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html
=> fix label for GHG offsets in calanderized table

src/app/shared/settings-forms/default-units-form/default-units-form.component.html
=> update layout of settings form for units

src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.ts
=> quick fix to emissions calcs in meter reading form

src/app/account/account-dashboard/energy-use-stacked-bar-chart/energy-use-stacked-bar-chart.component.ts, src/app/account/account-dashboard/facilities-table/facilities-table.component.html, src/app/account/account-dashboard/facilities-table/facilities-table.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-donut/account-report-donut.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-facility-bar-chart/account-report-facility-bar-chart.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-facility-summary-table/account-report-facility-summary-table.component.html, src/app/account/overview-report/basic-report/account-report/account-report.component.ts, src/app/account/overview-report/basic-report/facility-report/facility-report-meters-table/facility-report-meters-table.component.html, src/app/facility/facility-dashboard/meters-table/meters-table.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/facility/utility-data/meter-grouping/meter-grouping.service.ts, src/app/indexedDB/utilityMeter-db.service.ts, src/app/models/calanderization.ts, src/app/models/dashboard.ts, src/app/models/idb.ts, src/app/models/visualization.ts, src/app/shared/example-data/Better_Plants_Example.ts, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/dashboard.service.ts, src/app/shared/helper-services/meter-summary.service.ts, src/app/shared/helper-services/visualization.service.ts
connects #705 
initial location and market based multiplier logic added
further math lookups to come
=> update meters to have location and market based emissions multipliers

package.json, src/app/shared/helper-services/export-to-excel-template.service.ts
=> fix export to excel predictor bug and bump up version for release

src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/models/calanderization.ts, src/app/shared/helper-services/calanderization.service.ts
=> fix calanderization page with updated emissions variables

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts
=> filter scope options based on utility

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts
=> fixes to site to source display logic

src/app/account/overview-report/basic-report/account-report/account-report-donut/account-report-donut.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-facility-bar-chart/account-report-facility-bar-chart.component.html, src/app/account/overview-report/basic-report/account-report/account-report-facility-bar-chart/account-report-facility-bar-chart.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-facility-summary-table/account-report-facility-summary-table.component.html, src/app/account/overview-report/basic-report/account-report/account-report-utility-usage-bar-chart/account-report-utility-usage-bar-chart.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-utility-usage-table/account-report-utility-usage-table.component.html, src/app/account/overview-report/basic-report/account-report/account-report.component.html, src/app/account/overview-report/basic-report/facility-report/facility-report-bar-chart/facility-report-bar-chart.component.html, src/app/account/overview-report/basic-report/facility-report/facility-report-bar-chart/facility-report-bar-chart.component.ts, src/app/account/overview-report/basic-report/facility-report/facility-report-meters-table/facility-report-meters-table.component.html, src/app/account/overview-report/basic-report/facility-report/facility-report-utility-usage-table/facility-report-utility-usage-table.component.html, src/app/account/overview-report/overview-report-menu/overview-report-menu.component.ts, src/app/account/overview-report/overview-report.service.ts, src/app/models/overview-report.ts, src/app/shared/helper-services/dashboard.service.ts
=> update overview reports with location/market emissions

src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/models/electricityFilter.ts
connects #727 
updated the filters, forms and tables for electricity meter data to match the new fields from the import issues.
=> Update electricity forms and table with new fields

src/app/account/account-home/account-home.component.html, src/app/account/account-settings/account-settings.component.html, src/app/account/account-settings/account-settings.component.ts, src/app/core-components/sidebar/facility-list.pipe.ts, src/app/core-components/sidebar/sidebar.component.html, src/app/core-components/sidebar/sidebar.component.ts, src/app/indexedDB/facility-db.service.ts, src/app/models/idb.ts
connects #736 
use ordering number set in account settings for order of facility list in the sidebar
=> update facility list in sidebar to use ordering

src/app/shared/label-with-tooltip/labelTooltips.ts, src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.html, src/app/upload-data/upload-data.module.ts, tsconfig.json
=> add tooltip to select worksheet and facility labels

src/app/help-panel/help-panel.component.html, src/app/help-panel/help-panel.component.ts, src/app/help-panel/help-panel.module.ts, src/app/help-panel/setup-wizard-help/account-setup-help/account-setup-help.component.html, src/app/help-panel/setup-wizard-help/account-setup-help/account-setup-help.component.spec.ts, src/app/help-panel/setup-wizard-help/account-setup-help/account-setup-help.component.ts, src/app/help-panel/setup-wizard-help/confirm-new-account-help/confirm-new-account-help.component.html, src/app/help-panel/setup-wizard-help/confirm-new-account-help/confirm-new-account-help.component.spec.ts, src/app/help-panel/setup-wizard-help/confirm-new-account-help/confirm-new-account-help.component.ts, src/app/help-panel/setup-wizard-help/facility-setup-help/facility-setup-help.component.html, src/app/help-panel/setup-wizard-help/facility-setup-help/facility-setup-help.component.spec.ts, src/app/help-panel/setup-wizard-help/facility-setup-help/facility-setup-help.component.ts, src/app/help-panel/setup-wizard-help/setup-wizard-help.component.html, src/app/help-panel/setup-wizard-help/setup-wizard-help.component.spec.ts, src/app/help-panel/setup-wizard-help/setup-wizard-help.component.ts, src/app/help-panel/setup-wizard-help/setup-wizard-help.module.ts, src/app/help-panel/setup-wizard-help/welcome-help/welcome-help.component.html, src/app/help-panel/setup-wizard-help/welcome-help/welcome-help.component.spec.ts, src/app/help-panel/setup-wizard-help/welcome-help/welcome-help.component.ts, tsconfig.json
=> add help text for new account creation

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.html
=> fix toggle switch layout bug

src/app/upload-data/upload-data.service.ts
connects #755 
fix missing zip and meter name bugs from template
=> fix minor import bugs with missing fields

src/app/account/account-dashboard/energy-use-stacked-bar-chart/energy-use-stacked-bar-chart.component.ts, src/app/shared/helper-services/dashboard.service.ts, src/app/upload-data/upload-data.service.ts
connects #757 
energy unit was not being set properly on import.
hot fix stacked bar chart updating
=> quick fixes from alex review

src/app/account/account-analysis/account-analysis-results/annual-account-analysis/annual-account-analysis.component.html, src/app/account/account-analysis/account-analysis-results/annual-account-analysis/annual-account-analysis.component.ts, src/app/account/account-analysis/account-analysis-results/monthly-account-analysis/monthly-account-analysis.component.html, src/app/account/account-analysis/account-analysis-results/monthly-account-analysis/monthly-account-analysis.component.ts, src/app/account/account-analysis/account-analysis.module.ts, src/app/account/account-analysis/account-analysis.service.ts, src/app/facility/analysis/run-analysis/facility-analysis/annual-facility-analysis/annual-facility-analysis.component.html, src/app/facility/analysis/run-analysis/facility-analysis/monthly-facility-analysis/monthly-facility-analysis.component.html, src/app/facility/analysis/run-analysis/group-analysis/annual-analysis-summary/annual-analysis-summary.component.html, src/app/facility/analysis/run-analysis/group-analysis/monthly-analysis-summary/monthly-analysis-summary.component.html, src/app/shared/calculating-spinner/calculating-spinner.component.html, src/app/shared/calculating-spinner/calculating-spinner.component.ts, src/app/web-workers/annual-account-analysis.worker.ts, src/app/web-workers/classes/annualAccountAnalysisSummaryClass.ts, src/app/web-workers/classes/annualAnalysisSummaryDataClass.ts, src/app/web-workers/classes/monthlyAccountAnalysisClass.ts, src/app/web-workers/classes/monthlyAccountAnalysisDataClass.ts, src/app/web-workers/classes/monthlyFacilityAnalysisClass.ts, src/app/web-workers/monthly-account-analysis.worker.ts
=> Use web workers for account analysis

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/editMeterOptions.ts
=> change Biomass name

src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.html, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.ts, src/app/facility/analysis/analysis.component.html, src/app/facility/analysis/analysis.component.ts, src/app/facility/utility-data/meter-grouping/edit-meter-group-form/edit-meter-group-form.component.html, src/app/facility/utility-data/meter-grouping/edit-meter-group-form/edit-meter-group-form.component.ts, src/app/facility/utility-data/meter-grouping/meter-grouping.component.html, src/app/facility/utility-data/meter-grouping/meter-grouping.component.ts, src/app/facility/utility-data/meter-grouping/meter-grouping.service.ts, src/app/indexedDB/utilityMeterGroup-db.service.ts, src/app/models/calanderization.ts, src/app/models/idb.ts
connects #729 
hotfix add group types back in for meter group creation
=> Add error messaging to prevent bugs in facility analysis

src/app/account/account-analysis/account-analysis-results/annual-account-analysis/annual-account-analysis.component.ts, src/app/account/account-analysis/account-analysis-results/monthly-account-analysis/monthly-account-analysis.component.ts, src/app/account/account-home/account-home-summary/account-home-summary.component.html, src/app/account/account-home/account-home-summary/account-home-summary.component.ts, src/app/account/account-home/account-home.component.ts, src/app/account/account-home/account-home.service.ts, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.html, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.ts, src/app/facility/facility-home/facility-home.component.ts, src/app/facility/facility-home/facility-home.service.ts
=> update account and facility home screens to use web workers for analysis

src/app/account/account-dashboard/account-dashboard.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts, src/app/upload-data/upload-data.service.ts
=> update import template logic to set defaults

src/app/account/overview-report/better-plants-report-menu/better-plants-report-menu.component.ts, src/app/account/overview-report/better-plants-report/better-plants-report.component.html, src/app/account/overview-report/better-plants-report/better-plants-report.component.ts, src/app/account/overview-report/overview-report.module.ts, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.ts, src/app/web-workers/better-plants-report.worker.ts, src/app/web-workers/classes/betterPlantsEnergySummaryClass.ts, src/app/web-workers/classes/betterPlantsReportClass.ts
=> Web worker for Better Plants Report

src/app/facility/facility-dashboard/facility-bar-chart/facility-bar-chart.component.ts, src/app/facility/facility-dashboard/facility-stacked-area-chart/facility-stacked-area-chart.component.ts, src/app/setup-wizard/setup-confirmation/setup-confirmation.component.html, src/app/setup-wizard/setup-confirmation/setup-confirmation.component.ts, src/app/setup-wizard/setup-welcome/setup-welcome.component.html, src/app/setup-wizard/setup-wizard-banner/setup-wizard-banner.component.html, src/app/shared/settings-forms/default-units-form/default-units-form.component.html, src/app/upload-data/data-setup/file-setup/confirm-readings/confirm-readings.component.ts, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.html, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.ts, src/app/upload-data/file-upload/file-upload.component.html, src/app/upload-data/file-upload/file-upload.component.ts, src/app/upload-data/upload-data.service.ts
connects #762 
- Add "Corporate" to account setup
- Change unit labels to "Volume Unit (Gases)" and "Volume Unit (Liquids)"
- "Finish Setup" for submitting new account
- Messaging for upload file not working
- Add water group for import
- Auto-Group button in import
- Toggle calendarize meters
- Including water in energy rollups on home screen
=> Various small fixes from review

src/app/facility/utility-data/meter-grouping/edit-meter-group-form/edit-meter-group-form.component.ts, src/app/indexedDB/analysis-db.service.ts
=> only add energy groups to analysis

src/app/account/account-analysis/account-analysis-results/annual-account-analysis/annual-account-analysis.component.ts, src/app/account/account-analysis/account-analysis-results/monthly-account-analysis/monthly-account-analysis.component.ts, src/app/account/account-home/account-home.component.ts, src/app/account/overview-report/better-plants-report/better-plants-report.component.ts, src/app/core-components/import-backup-modal/import-backup-modal.component.ts, src/app/facility/analysis/run-analysis/facility-analysis/annual-facility-analysis/annual-facility-analysis.component.ts, src/app/facility/analysis/run-analysis/facility-analysis/monthly-facility-analysis/monthly-facility-analysis.component.ts, src/app/facility/analysis/run-analysis/group-analysis/annual-analysis-summary/annual-analysis-summary.component.ts, src/app/facility/analysis/run-analysis/group-analysis/monthly-analysis-summary/monthly-analysis-summary.component.ts, src/app/facility/facility-home/facility-home.component.ts, src/app/setup-wizard/setup-welcome/setup-welcome.component.css, src/app/setup-wizard/setup-welcome/setup-welcome.component.html, src/app/setup-wizard/setup-welcome/setup-welcome.component.ts
connects #784
connects #782 
navigate to account home when loading account backup
add link to welcome screen to go to next page
=> quick fixes account setup

src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/visualization.service.ts, src/app/upload-data/upload-data.service.ts
=> fix emissions defaults and math

src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.ts, src/app/account/overview-report/overview-report-banner/overview-report-banner.component.ts, src/app/facility/analysis/analysis-banner/analysis-banner.component.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.ts, src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/utility-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/help-panel/help-panel.component.ts, src/app/help-panel/setup-wizard-help/setup-wizard-help.component.ts, src/app/help-panel/upload-data-help/upload-data-help.component.ts, src/app/help-panel/utility/energy-consumption-help/energy-consumption-help.component.ts, src/app/models/idb.ts, src/app/models/meterDataFilter.ts, src/app/setup-wizard/setup-wizard-footer/setup-wizard-footer.component.ts
=> add filters to general data table

src/app/upload-data/upload-data.service.ts
=> check import predictors for data

src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.html
=> fix absolute/intensity label in goals

src/app/facility/analysis/analysis-validation.service.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/shared/helper-services/calanderization.service.ts
=> remove multiplier division for site/source in emissions calcs

src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.html, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.html, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/shared/helper-pipes/helper-pipes.module.ts, src/app/shared/helper-pipes/year-display.pipe.spec.ts, src/app/shared/helper-pipes/year-display.pipe.ts, src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.html, src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.ts
=> add fiscal year pipe for displaying dropdowns and years with FY

src/app/upload-data/data-setup/file-setup/confirm-predictors/confirm-predictors.component.html, src/app/upload-data/upload-data.service.ts
=> update predictor uploading from template to assume production

src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.ts, src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.html, src/app/web-workers/classes/monthlyAccountAnalysisClass.ts
=> add messaging for skip/haven't visited facility in account analysis

src/app/shared/settings-forms/default-units-form/default-units-form.component.html
=> add default units label

src/app/shared/helper-services/export-to-excel-template.service.ts
=> fix bug 819 (export to template)

src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts
=> fix bug 817 (manual regression constant entry)

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/utility-meters-table/utility-meters-table.component.html, src/app/upload-data/upload-data.service.ts
=> Enforce emissions boolean options for agreement types

src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> add SEP validation check for model variables

src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> change SEP model check notes

src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> fix invalid model bug

src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> fixes to standard dev notes

src/app/account/overview-report/better-plants-report-menu/better-plants-report-menu.component.ts, src/app/account/overview-report/better-plants-report/better-plants-report.component.ts, src/app/facility/utility-data/calanderization/data-application-menu/data-application-menu.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/facility/utility-data/meter-grouping/meter-grouping.service.ts, src/app/models/calanderization.ts, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/meter-summary.service.ts, src/app/shared/shared-analysis/calculations/getFiscalYear.ts, src/app/web-workers/classes/betterPlantsEnergySummaryClass.ts, src/app/web-workers/classes/betterPlantsReportClass.ts, src/app/web-workers/classes/helperService.ts
=> FY fixes for better plants report and annual predictor usage

package-lock.json, package.json
=> update for v0.8.1-alpha release

src/app/upload-data/upload-data.service.ts
=> fixes for issue 757

src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts
=> hide consumption column if all 0s

src/app/indexedDB/account-db.service.ts
=> energy and water goals default to Intensity

src/app/shared/settings-forms/settings-forms.service.ts
=> fix saving volume gas unit

src/app/upload-data/file-upload/file-upload.component.css, src/app/upload-data/file-upload/file-upload.component.html, src/app/upload-data/file-upload/file-upload.component.ts
=> add drag and drop indicators to file upload input and help text

src/app/account/account-settings/account-settings.component.css, src/app/account/account-settings/account-settings.component.html, src/app/account/account-settings/account-settings.component.ts, src/styles/popupsWindows.css
=> add ability to apply account settings to facilities

src/app/web-workers/classes/helperService.ts
=> fix fiscal year filter meter data call

src/app/facility/analysis/analysis.module.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.css, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.spec.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.css, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.ts, src/app/models/analysis.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts, src/app/shared/shared-analysis/monthly-analysis-summary-table/monthly-analysis-summary-table.component.html
connects #821 
add ability to inspect different regression models with graphs and SEP validation numbers
=> add regression model inspection

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/models/idb.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> add user defined notes to regression model

src/app/upload-data/upload-data.service.ts
=> enforce electricity meter to be energy

src/app/account/overview-report/better-plants-report/facility-performance-table/facility-performance-table.component.ts
=> add in missing performance range in BP report

src/app/indexedDB/facility-db.service.ts, src/app/indexedDB/predictors-db.service.ts, src/app/indexedDB/utilityMeter-db.service.ts, src/app/indexedDB/utilityMeterData-db.service.ts, src/app/indexedDB/utilityMeterGroup-db.service.ts, src/app/upload-data/upload-data.service.ts
=> use copies of data on import to not modify existing numbers

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.html
=> add spacing to additional model notes

src/app/facility/facility-overview/facility-overview.component.ts, src/app/web-workers/classes/dashboard/accountSummaryClass.ts, src/app/web-workers/classes/dashboard/facilitySummaryClass.ts, src/app/web-workers/classes/helper-functions/calanderizationFunctions.ts
=> fix monthly usage calculation for monthly overview charts

src/app/facility/analysis/analysis.module.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-number.pipe.spec.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-number.pipe.ts
=> cleanup regression model table digits

src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.css, src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.html
=> Move facility select tabs to side nav in account analysis

src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.ts, src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.ts, src/app/facility/analysis/analysis-validation.service.ts, src/app/indexedDB/db-changes.service.ts, src/app/shared/helper-services/shared-data.service.ts
=> fixes to changing account causing analysis errors

src/app/account/account-analysis/account-analysis-results/annual-account-analysis/annual-account-analysis.component.html, src/app/account/account-analysis/account-analysis-results/monthly-account-analysis/monthly-account-analysis.component.html, src/app/account/account-overview/account-overview-banner/account-overview-banner.component.css, src/app/account/account-overview/account-overview-banner/account-overview-banner.component.html, src/app/facility/analysis/run-analysis/facility-analysis/annual-facility-analysis/annual-facility-analysis.component.html, src/app/facility/analysis/run-analysis/facility-analysis/monthly-facility-analysis/monthly-facility-analysis.component.html, src/app/facility/analysis/run-analysis/group-analysis/annual-analysis-summary/annual-analysis-summary.component.html, src/app/facility/analysis/run-analysis/group-analysis/monthly-analysis-summary/monthly-analysis-summary.component.html, src/app/facility/facility-overview/facility-overview-banner/facility-overview-banner.component.css, src/app/facility/facility-overview/facility-overview-banner/facility-overview-banner.component.html, src/app/facility/utility-data/calanderization/calanderization.component.css, src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/meter-grouping/meter-grouping.component.css, src/app/facility/utility-data/meter-grouping/meter-grouping.component.html, src/styles/buttons.css
=> Group meters page styling updates

src/app/facility/utility-data/calanderization/calanderization-filter/calanderization-filter.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts
=> show site to source for Other Energy meters

src/app/account/overview-report/better-plants-report-menu/better-plants-report-menu.component.ts, src/app/shared/shared-analysis/annual-analysis-summary-table/annual-analysis-summary-table.component.html, src/app/shared/shared-analysis/monthly-analysis-summary-table/monthly-analysis-summary-table.component.html
=> quick updates to analysis data tables

src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.ts, src/app/account/account-settings/account-settings.component.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.ts, src/app/indexedDB/analysis-db.service.ts
connects #902 
auto select regression and generate models when visiting the page
force user to select a model
order by adjusted r2
=> set regression as the default analysis type

package-lock.json, package.json, src/app/shared/helper-services/calanderization.service.ts
=> updates for beta release

src/app/shared/helper-services/calanderization.service.ts
=> Extra month fix

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html
=> hide models when user defined model

src/app/account/overview-report/better-plants-report/primary-energy-consumption-table/primary-energy-consumption-table.component.html, src/app/account/overview-report/better-plants-report/primary-energy-consumption-table/primary-energy-consumption-table.component.ts, src/app/account/overview-report/overview-report-menu/overview-report-menu.component.html, src/app/facility/utility-data/meter-grouping/meter-grouping.component.html, src/app/facility/utility-data/predictor-data/predictor-data.component.html, src/app/models/overview-report.ts, src/app/shared/settings-forms/default-units-form/default-units-form.component.html, src/app/web-workers/classes/betterPlantsEnergySummaryClass.ts, src/styles/popupsWindows.css
connects #920 
hotfix overlay issue
=> add other energy to better plants report

src/app/account/account-overview/costs-overview/facility-cost-chart/facility-cost-chart.component.ts, src/app/account/account-overview/emissions-overview/facility-emissions-chart/facility-emissions-chart.component.ts, src/app/account/account-overview/energy-overview/facility-utility-usage-chart/facility-utility-usage-chart.component.ts, src/app/account/account-overview/water-overview/facility-water-chart/facility-water-chart.component.ts, src/app/facility/facility-overview/facility-cost-overview/cost-meters-overview-chart/cost-meters-overview-chart.component.ts, src/app/facility/facility-overview/facility-emissions-overview/emissions-meters-overview-chart/emissions-meters-overview-chart.component.ts, src/app/facility/facility-overview/facility-energy-overview/energy-meters-overview-chart/energy-meters-overview-chart.component.ts, src/app/facility/facility-overview/facility-water-overview/water-meters-overview-chart/water-meters-overview-chart.component.ts, src/app/shared/helper-services/export-to-excel-template.service.ts, src/app/upload-data/upload-data.service.ts
=> re-format donut charts in overview to handle many facilities

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/indexedDB/analysis-db.service.ts
=> fix create analysis logic

src/app/account/account-settings/account-settings.component.ts, src/app/account/overview-report/better-plants-report-menu/better-plants-report-menu.component.html, src/app/account/overview-report/better-plants-report/better-plants-report.component.ts, src/app/calculations/better-plants-calculations/betterPlantsReportClass.ts, src/app/facility/facility-settings/facility-settings.component.ts, src/app/indexedDB/db-changes.service.ts
connects #930 
fixes to deleting facility and better plants report with skipped facilities
=> Better plants report skipped facilities bug

src/app/account/account-overview/account-overview-banner/account-overview-banner.component.html, src/app/account/account-overview/emissions-overview/facility-emissions-chart/facility-emissions-chart.component.ts, src/app/account/account-overview/emissions-overview/facility-emissions-map/facility-emissions-map.component.ts, src/app/account/account-overview/emissions-overview/facility-emissions-table/facility-emissions-table.component.html, src/app/account/account-overview/emissions-overview/monthly-emissions-chart/monthly-emissions-chart.component.ts, src/app/account/account-overview/emissions-overview/utility-emissions-table/utility-emissions-table.component.html, src/app/account/overview-report/basic-report/account-report/account-report-donut/account-report-donut.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-facility-bar-chart/account-report-facility-bar-chart.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-facility-summary-table/account-report-facility-summary-table.component.html, src/app/account/overview-report/basic-report/account-report/account-report-utility-usage-bar-chart/account-report-utility-usage-bar-chart.component.ts, src/app/account/overview-report/basic-report/account-report/account-report-utility-usage-table/account-report-utility-usage-table.component.html, src/app/account/overview-report/basic-report/facility-report/facility-report-bar-chart/facility-report-bar-chart.component.ts, src/app/account/overview-report/basic-report/facility-report/facility-report-meters-table/facility-report-meters-table.component.html, src/app/account/overview-report/basic-report/facility-report/facility-report-utility-usage-table/facility-report-utility-usage-table.component.html, src/app/facility/facility-overview/facility-emissions-overview/emissions-meters-overview-chart/emissions-meters-overview-chart.component.ts, src/app/facility/facility-overview/facility-emissions-overview/emissions-meters-overview-table/emissions-meters-overview-table.component.html, src/app/facility/facility-overview/facility-emissions-overview/emissions-meters-usage-chart/emissions-meters-usage-chart.component.ts, src/app/facility/facility-overview/facility-emissions-overview/emissions-utilities-chart/emissions-utilities-chart.component.ts, src/app/facility/facility-overview/facility-emissions-overview/emissions-utilities-table/emissions-utilities-table.component.html, src/app/facility/facility-overview/facility-emissions-overview/facility-emissions-monthly-chart/facility-emissions-monthly-chart.component.ts, src/app/facility/facility-overview/facility-overview-banner/facility-overview-banner.component.html, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html
=> fix labels for emissions CO2e

src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/shared/helper-services/calanderization.service.ts
=> emissions always in site energy

src/app/shared/helper-services/energy-use-calculations.service.ts
=> fix conversion for natural gas heating capacity

src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.css, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.html, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.ts, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.css, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.html, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.spec.ts, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.ts, src/app/account/account-analysis/account-analysis.module.ts, src/app/account/overview-report/better-plants-report-menu/better-plants-report-menu.component.html, src/app/account/overview-report/overview-report-dashboard/overview-report-dashboard.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.css, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.html, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.css, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.html, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.spec.ts, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.ts, src/app/facility/analysis/analysis.module.ts, src/app/facility/analysis/analysis.service.ts, src/app/models/idb.ts, src/app/shared/helper-pipes/analysis-type-label.pipe.spec.ts, src/app/shared/helper-pipes/analysis-type-label.pipe.ts, src/app/shared/helper-pipes/helper-pipes.module.ts, src/styles/typography.css
Select the analysis for a given year. This will translate to other portions of the application like home screens and rollups.
Design enhancements to dashboards
connects #743
=> Add select analysis functionality

src/app/shared/helper-services/export-to-excel-template.service.ts
=> add letters to support exporting more predictors

src/app/account/account-analysis/account-analysis-results/account-analysis-results.component.ts, src/app/account/account-home/account-home-summary/account-home-summary.component.html, src/app/account/account-home/account-home-summary/account-home-summary.component.ts, src/app/account/account-home/account-home.component.ts, src/app/account/account-home/account-home.service.ts, src/app/account/account-home/facility-card/facility-card.component.html, src/app/account/account-home/facility-card/facility-card.component.ts, src/app/calculations/analysis-calculations/annualAccountAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualFacilityAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualGroupAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyGroupAnalysisClass.ts, src/app/calculations/better-plants-calculations/betterPlantsReportClass.ts, src/app/facility/analysis/run-analysis/facility-analysis/facility-analysis.component.ts, src/app/facility/analysis/run-analysis/group-analysis/monthly-analysis-summary/monthly-analysis-summary.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.ts, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.html, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.ts, src/app/facility/facility-home/facility-home.component.ts, src/app/facility/facility-home/facility-home.service.ts, src/app/web-workers/annual-account-analysis.worker.ts, src/app/web-workers/annual-facility-analysis.worker.ts, src/app/web-workers/monthly-group-analysis.worker.ts
connects #797 
add ability to calculate analysis to latest billed entry and update home screens to use
=> Graphs on home screen show to latest billed entry

src/app/account/account-home/account-home-summary/account-home-summary.component.html, src/app/account/account-home/facility-card/facility-card.component.html, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.html
=> add fiscal year to home screens

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/upload-data/data-setup/file-setup/confirm-predictors/confirm-predictors.component.html, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.ts
=> don't lock electricity to kwh on source change

src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.css, src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.html
=> fix facility select scrolling in account analysis

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html
=> allow changing electricity units with meter data

src/app/upload-data/data-setup/file-setup/confirm-readings/confirm-readings.component.ts, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.ts, src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.ts
=> trim whitespace in headers on parse of excel data

package.json
=> update version number for 0.9.2-beta release

src/app/shared/shared-analysis/monthly-analysis-summary-graph/monthly-analysis-summary-graph.component.ts
=> update labels for monthly analysis graph

src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.html, src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.ts
=> trim headers for upload

src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.html, src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.ts, src/app/facility/analysis/analysis-footer/analysis-footer.component.html
=> remove continue button at end of account analysis

src/app/upload-data/data-setup/data-setup-banner/data-setup-banner.component.html, src/app/upload-data/data-setup/data-setup-banner/data-setup-banner.component.ts, src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.ts, src/app/upload-data/file-upload/file-upload.component.html
=> add are you sure dialog box to start over upload

src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html
=> update emissions labels in utility data

src/app/account/account-settings/account-settings.component.html
=> fix window overlay in account settings

src/app/facility/facility-settings/facility-settings.component.ts, src/app/shared/settings-forms/settings-forms.service.ts
=> add electricity units to facility account matching check

src/app/shared/helper-services/calanderization.service.ts, src/app/upload-data/upload-data.service.ts
=> read in values as numbers from excel

src/app/shared/helper-services/export-to-excel-template.service.ts
=> fix export to template dates

src/app/facility/utility-data/predictor-data/predictor-data.component.ts
=> fix link for predictors

src/app/shared/helper-services/energy-units-helper.service.ts
=> fix electricity unit warning in meter form

src/app/upload-data/file-upload/file-upload.component.ts, src/app/upload-data/upload-data.service.ts
=> fix zip bug

src/app/upload-data/upload-data.service.ts
=> fix importing issue

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/shared/helper-services/energy-use-calculations.service.ts, src/app/shared/unitOptions.ts
=> fix heat capacity for large units and add missing units to dropdown

src/app/shared/shared-analysis/monthly-analysis-summary-graph/monthly-analysis-summary-graph.component.ts
=> updated graph labels

src/app/shared/helper-services/export-to-excel-template.service.ts
=> add calanderization options to export to template

src/app/core-components/import-backup-modal/import-backup-modal.component.html, src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/shared/helper-services/calanderization.service.ts
=> RECs calcs in MWh and display fixes

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/editMeterOptions.ts
=> update self generation label to on-site

src/app/shared/helper-services/calanderization.service.ts
=> fix non electricity emissions calcs

src/app/facility/analysis/analysis.service.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.ts
=> fix baseline adjustments bug

src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClass.ts
=> round 0s for baseline adjustments

src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/calanderization/calanderization.component.ts
=> add warning for meters without data in calanderization tab

src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/energy-use-calculations.service.ts
=> do emissions calcs in MMBtu

src/app/shared/helper-services/backup-data.service.ts
=> parse dates on import of account backups

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/editMeterOptions.ts, src/app/shared/helper-services/energy-use-calculations.service.ts
=> fuel emissions in CO2e

src/app/shared/shared-analysis/annual-analysis-summary-graph/annual-analysis-summary-graph.component.ts
=> fix annual analysis graph label

src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClass.ts, src/app/core-components/import-backup-modal/import-backup-modal.component.html
=> updates to calculations for adjusted values

src/app/facility/utility-data/predictor-data/edit-predictors/edit-predictors.component.html, src/app/facility/utility-data/predictor-data/predictor-data.component.html, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.ts, src/app/upload-data/upload-data.service.ts
=> fix predictor import bugs

src/app/upload-data/file-upload/file-upload.component.html
=> export template link uses unmodified template

src/app/facility/utility-data/calanderization/calanderization-chart/calanderization-chart.component.ts, src/app/facility/utility-data/meter-grouping/meter-group-chart/meter-group-chart.component.ts, src/app/facility/visualization/time-series/time-series.component.ts
=> apply tickmode to both axis

src/app/account/account-reports/better-plants-report/better-plants-report.component.ts
=> fix skipped analysis items bug

src/app/account/account-settings/account-settings.component.html
=> move account portfolio action btns

src/app/account/account-analysis/account-analysis-results/monthly-account-analysis/monthly-account-analysis.component.html, src/app/facility/analysis/run-analysis/facility-analysis/monthly-facility-analysis/monthly-facility-analysis.component.html, src/app/facility/analysis/run-analysis/group-analysis/monthly-analysis-summary/monthly-analysis-summary.component.html, src/app/shared/shared-analysis/monthly-analysis-summary-savings-graph/monthly-analysis-summary-savings-graph.component.html, src/app/shared/shared-analysis/monthly-analysis-summary-savings-graph/monthly-analysis-summary-savings-graph.component.spec.ts, src/app/shared/shared-analysis/monthly-analysis-summary-savings-graph/monthly-analysis-summary-savings-graph.component.ts, src/app/shared/shared-analysis/shared-analysis.module.ts
=> Issue 1075

src/app/account/account-overview/account-overview-banner/account-overview-banner.component.ts, src/app/facility/facility-overview/facility-overview-banner/facility-overview-banner.component.ts, src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/calanderization/calanderization.component.ts, src/app/facility/utility-data/calanderization/data-application-menu/data-application-menu.component.html, src/app/facility/utility-data/calanderization/data-application-menu/data-application-menu.component.ts, src/app/facility/utility-data/predictor-data/predictor-data.component.html, src/app/models/idb.ts, src/app/setup-wizard/setup-confirmation/setup-confirmation.component.html, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/export-to-excel-template.service.ts, src/styles/buttons.css
=> Add annual calendarization method

src/app/shared/helper-services/export-to-excel-template.service.ts
=> export volume for non energy consumption meters

src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.html, src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.ts, src/app/facility/analysis/account-analysis-list/account-analysis-list.component.html, src/app/facility/analysis/account-analysis-list/account-analysis-list.component.ts, src/app/facility/analysis/analysis-footer/analysis-footer.component.html, src/app/facility/analysis/analysis-footer/analysis-footer.component.ts, src/app/facility/utility-data/calanderization/data-application-menu/data-application-menu.component.html, src/app/shared/data-overview/meter-usage-donut/meter-usage-donut.component.ts, src/app/shared/data-overview/utilities-usage-chart/utilities-usage-chart.component.ts
=> additions to finish of analysis and other quick fixes

package.json, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts
=> Issue 1095

main.js, package.json, src/app/core-components/electron-update/electron-update.component.css, src/app/core-components/electron-update/electron-update.component.html, src/app/core-components/electron-update/electron-update.component.ts, src/app/core-components/header/header.component.html, src/app/core-components/header/header.component.ts
=> fix auto updater, update version for quick fix release

main.js, package-lock.json, package.json, src/app/core-components/electron-update/electron-update.component.css, src/app/core-components/electron-update/electron-update.component.html, src/app/core-components/electron-update/electron-update.component.ts, src/app/core-components/header/header.component.html, src/app/core-components/header/header.component.ts
updates for latest release v0.9.5-beta
=> VERIFI v0.9.5-beta

package-lock.json, src/app/account/account-analysis/account-analysis-results/annual-account-analysis/annual-account-analysis.component.html, src/app/account/account-analysis/account-analysis-results/monthly-account-analysis/monthly-account-analysis.component.html, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html, src/app/calculations/analysis-calculations/monthlyAccountAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts, src/app/facility/analysis/run-analysis/group-analysis/annual-analysis-summary/annual-analysis-summary.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.ts, src/app/facility/analysis/run-analysis/group-analysis/monthly-analysis-summary/monthly-analysis-summary.component.html
connects #1101 
hotfix: hide "Choose Column" dropdown in analysis when displaying graphs
=> fix baseline adjustments for fiscal year facilities

src/app/facility/visualization/visualization-banner/visualization-banner.component.html
=> re-organize visualization tabs

src/app/facility/visualization/correlation-plot-menu/correlation-plot-menu.component.html
=> re-order visualization menu

src/app/electron/electron.service.ts
=> fix web disclaimer text

src/app/shared/shared-analysis/monthly-analysis-summary-savings-graph/monthly-analysis-summary-savings-graph.component.ts
=> rolling 12 month improvement used for graph

src/app/setup-wizard/setup-facilities/setup-facilities.component.css, src/app/setup-wizard/setup-facilities/setup-facilities.component.html, src/app/setup-wizard/setup-facilities/setup-facilities.component.ts
=> add drag/drop styling for file input in account setup

src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.ts, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts
=> will set selected analysis item by default

src/app/facility/visualization/visualization.component.css, src/app/facility/visualization/visualization.component.html
=> fix scrolling for visualization

src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.html, src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.ts
=> add option to show/hide hidden tabs in upload wizard

src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts
=> add column header row for non electricity utility data table

src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/utility-meter-data-table.component.html, src/app/shared/shared-analysis/analysis-summary-table-filter/analysis-summary-table-filter.component.html, src/app/shared/shared-analysis/analysis-summary-table-filter/analysis-summary-table-filter.component.ts
=> Enhancements to table filters

src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> fix regression validity check

src/app/help-panel/account-help/account-reports-help/better-plants-report-help/better-plants-report-help.component.html, src/app/help-panel/account-help/account-reports-help/report-setup-help/report-setup-help.component.html
=> updates for better plants report help

src/app/help-panel/facility-help/facility-utility-help/energy-consumption-help/edit-meter-help/edit-meter-help.component.html
=> help text added for site to source

src/app/help-panel/facility-help/facility-utility-help/meter-grouping-help/meter-grouping-help.component.html
=> updated grouping help text

src/app/calculations/analysis-calculations/monthlyAccountAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyGroupAnalysisClass.ts
connects #1132 
account analysis also runs to min facility analysis end date
=> stop analysis calculations at latest meter readings and predictors

src/app/shared/shared-analysis/monthly-analysis-summary-graph/monthly-analysis-summary-graph.component.ts, src/app/shared/shared-analysis/monthly-analysis-summary-savings-graph/monthly-analysis-summary-savings-graph.component.ts
=> update monthly analysis savings graph to bar chart

src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.ts
=> fix auto group on import for Other Energy and Waste Water

src/app/indexedDB/analysis-db.service.ts, src/app/models/degreeDays.ts, src/app/shared/helper-services/degree-days.service.ts, src/app/weather-data/annual-station-data/annual-station-data.component.ts, src/app/weather-data/annual-station-data/annual-station-table/annual-station-table.component.html, src/app/weather-data/annual-station-data/annual-station-table/annual-station-table.component.ts, src/app/weather-data/daily-station-data/daily-station-data.component.html, src/app/weather-data/monthly-station-data/monthly-station-table/monthly-station-table.component.html
quick fix overriding predictors selected for analysis when generating weather data
connects #85
=> updates to degree days calculations

src/app/upload-data/data-setup/file-setup/confirm-predictors/confirm-predictors.component.html, src/app/upload-data/data-setup/file-setup/confirm-predictors/confirm-predictors.component.ts, src/app/upload-data/data-setup/file-setup/confirm-readings/confirm-readings.component.html, src/app/upload-data/data-setup/file-setup/confirm-readings/confirm-readings.component.ts, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.html, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.ts
=> add skip existing check for table header

src/app/shared/helper-services/export-to-excel-template.service.ts
=> replace periods with underscore to fix export to xlsx

src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.html, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis.component.html, src/app/models/idb.ts, src/app/shared/helper-pipes/analysis-type-label.pipe.ts
=> add ability to skip group in analysis

src/app/account/account-overview/account-overview-banner/account-overview-banner.component.ts, src/app/account/account-overview/account-overview.component.ts, src/app/calculations/dashboard-calculations/facilityOverviewClass.ts, src/app/facility/facility-overview/facility-overview-banner/facility-overview-banner.component.ts, src/app/facility/facility-overview/facility-overview.component.ts, src/app/facility/visualization/visualization-state.service.ts, src/app/facility/visualization/visualization.component.ts
=> Fix date range initialization on overview and visualization pages

package.json
=> update version number for release

src/app/facility/analysis/analysis.service.ts, src/app/models/analysis.ts, src/app/shared/shared-analysis/analysis-summary-table-filter/analysis-summary-table-filter.component.html, src/app/shared/shared-analysis/analysis-summary-table-filter/analysis-summary-table-filter.component.ts, src/app/shared/shared-analysis/annual-analysis-summary-table/annual-analysis-summary-table.component.ts
=> remove adjustment to baseline from filter options

src/app/help-panel/account-help/account-settings-help/account-settings-help.component.html, src/app/help-panel/facility-help/facility-settings-help/facility-settings-help.component.html
=> updates to settings help text after review

src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.ts, src/app/facility/utility-data/predictor-data/manage-predictors/predictors-table/predictors-table.component.ts, src/app/facility/utility-data/predictor-data/predictor-entries/predictor-entries-table/predictor-entries-table.component.ts, src/app/indexedDB/predictors-db.service.ts, src/app/models/degreeDays.ts, src/app/weather-data/annual-station-data/annual-station-data.component.html, src/app/weather-data/annual-station-data/annual-station-data.component.ts, src/app/weather-data/annual-station-data/annual-station-graph/annual-station-graph.component.ts, src/app/weather-data/annual-station-data/annual-station-table/annual-station-table.component.html, src/app/weather-data/annual-station-data/annual-station-table/annual-station-table.component.ts, src/app/weather-data/monthly-station-data/monthly-station-data.component.html, src/app/weather-data/monthly-station-data/monthly-station-data.component.ts, src/app/weather-data/monthly-station-data/monthly-station-graph/monthly-station-graph.component.ts, src/app/weather-data/monthly-station-data/monthly-station-table/monthly-station-table.component.html, src/app/weather-data/monthly-station-data/monthly-station-table/monthly-station-table.component.ts, src/app/weather-data/weather-data.component.html, src/app/weather-data/weather-data.component.ts, src/app/weather-data/weather-data.service.ts
connects #1167 
Ability to choose generating CDD/HDD or both from weather data
Setup for additional weather data to be added
=> Choose HDD/CDD or both for weather data

src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/convert-meter-data.service.ts
connects #1185 
connects #1186
=> fix label for water meters in monthly data and hide emissions columns

src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.ts, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.html, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.ts, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.ts, src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.html, src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.ts, src/app/app.component.ts, src/app/calculations/analysis-calculations/annualAccountAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualFacilityAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualGroupAnalysisSummaryClass.ts, src/app/calculations/shared-calculations/calculationsHelpers.ts, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.html, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.ts, src/app/facility/analysis/analysis-validation.service.ts, src/app/facility/analysis/analysis.service.ts, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.html, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.ts, src/app/indexedDB/account-analysis-db.service.ts, src/app/indexedDB/analysis-db.service.ts, src/app/indexedDB/facility-db.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/idb.ts
connects #967 
adds ability to set a baseline year different then the account/facility goals baseline year.
=> updates to set baseline year in analysis

src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.ts, src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.ts, src/app/account/account-home/account-home-summary/account-home-summary.component.html, src/app/account/account-home/facility-card/facility-card.component.ts, src/app/account/account-reports/account-report-setup/account-report-setup.component.ts, src/app/account/account-settings/account-settings.component.ts, src/app/core-components/header/header.component.html, src/app/core-components/header/search-bar/search-bar.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.ts, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/utility-meter-data-table.component.ts, src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.html, src/app/indexedDB/account-db.service.ts, src/app/indexedDB/utilityMeterData-db.service.ts, src/app/shared/helper-services/backup-data.service.ts, src/app/shared/helper-services/energy-use-calculations.service.ts, src/app/shared/helper-services/export-to-excel-template.service.ts, src/app/upload-data/data-setup/file-setup/confirm-and-submit/confirm-and-submit.component.ts, src/app/upload-data/data-setup/file-setup/identify-columns/identify-columns.component.ts, src/app/weather-data/annual-station-data/annual-station-data.component.html, src/app/weather-data/monthly-station-data/monthly-station-data.component.html
=> address various TODO's or create issues for bigger ones

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.ts
=> quick fix regression selection update validation

src/app/shared/helper-services/calanderization.service.ts
=> show monthly data if not calendarizing

src/app/facility/utility-data/calanderization/calanderization.component.html
=> hide site/source toggle for water meters in monthly data

src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.html, src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.ts, src/app/facility/utility-data/predictor-data/manage-predictors/manage-predictors.component.ts, src/app/facility/utility-data/predictor-data/manage-predictors/predictors-table/predictors-table.component.html, src/app/facility/utility-data/predictor-data/manage-predictors/predictors-table/predictors-table.component.ts, src/app/facility/utility-data/predictor-data/predictor-entries/predictor-entries-table/predictor-entries-table.component.html, src/app/facility/utility-data/predictor-data/predictor-tabs/predictor-tabs.component.html, src/app/facility/utility-data/predictor-data/predictor-tabs/predictor-tabs.component.ts, src/app/routing/facility.routes.ts, src/app/weather-data/weather-data.component.html, src/app/weather-data/weather-data.component.ts
connects #1216 
also handles creating predictors from weather data in facilities without predictor data.
=> Fix predictors bug for creating first predictor data

src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.ts, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/account/account-analysis/select-facility-analysis-items/select-facility-analysis-items.component.ts, src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.ts, src/app/account/account-reports/account-report-setup/account-report-setup.component.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyGroupAnalysisClass.ts, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.html, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.ts, src/app/facility/analysis/analysis-footer/analysis-footer.component.ts, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.html, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-menu/regression-model-menu.component.ts, src/app/facility/visualization/correlation-plot-menu/correlation-plot-menu.component.ts, src/app/indexedDB/analysis-db.service.ts, src/app/indexedDB/utilityMeterData-db.service.ts, src/app/models/idb.ts, src/app/shared/helper-services/analysis-validation.service.ts, src/app/shared/settings-forms/settings-forms.module.ts, src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.html
connects #990 
set "New Facility" option if baseline years for sustainability goals are different.
Updates to validation involved in setting baseline year.
=> Validation updates for baseline year changes

src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/models/idb.ts
=> add is estimated question to meter readings

src/app/indexedDB/facility-db.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/constantsAndTypes.ts, src/app/models/idb.ts, src/app/shared/settings-forms/general-information-form/general-information-form.component.html, src/app/shared/settings-forms/general-information-form/general-information-form.component.ts, src/app/shared/settings-forms/settings-forms.service.ts
=> add facility classification to settings

src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.html, src/app/indexedDB/predictors-db.service.ts, src/app/shared/settings-forms/settings-forms.service.ts
=> updates to new predictors, quickfix save facility area

src/app/upload-data/upload-data.service.ts
=> fixes to predictors re-upload

src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.html, src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.ts, src/app/indexedDB/predictors-db.service.ts
=> update workflow for create predictors

package-lock.json, package.json
=> update version number v0.10.1-beta

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter/edit-meter.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-bill.component.ts, src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.ts, src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.html, src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.ts, src/app/routing/can-deactivate.guard.spec.ts, src/app/routing/can-deactivate.guard.ts, src/app/routing/facility.routes.ts
=> add route gaurds to prevent navigation with unsaved changes

src/app/core-components/header/header.component.ts, src/app/core-components/import-backup-modal/import-backup-modal.component.html, src/app/core-components/import-backup-modal/import-backup-modal.component.ts
=> fixes to import backup modal

src/app/shared/shared-analysis/analysis-summary-table-filter/analysis-summary-table-filter.component.html
=> fix missing rolling 12 month improvement in annual analysis

src/app/account/account-settings/account-settings.component.ts
=> navigate to new facility when creating from account settings

src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/energy-units-helper.service.ts
=> fixes to other utility

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/shared/helper-services/energy-units-helper.service.ts
=> remove energy units from other utility

src/app/static-content/acknowledgments/acknowledgments.component.html
=> add chris to acknowledgments

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/editMeterOptions.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/utility-meter-data-table.component.html, src/app/shared/helper-services/calanderization.service.ts, src/app/shared/helper-services/energy-units-helper.service.ts
connects #1243
(wrong branch name)
=> add purchased compressed air

src/app/core-components/manage-accounts/manage-accounts.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/shared/helper-services/energy-use-calculations.service.ts, src/app/upload-data/upload-data.service.ts
connects #1127 
connects #1096
=> updated template and handle water intake/discharge

src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> updated messaging for SEP validation

src/app/shared/helper-services/calanderization.service.ts
=> make sure years are sorted properly

src/app/shared/helper-services/energy-units-helper.service.ts
=> correct unit for natural gas in energy

src/app/account/account-analysis/account-analysis-dashboard/account-analysis-dashboard.component.ts, src/app/account/account-reports/better-plants-report/better-plants-report.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-dashboard.component.ts, src/app/facility/facility-home/facility-home.component.ts, src/app/indexedDB/analysis-db.service.ts
=> quick fixes for conversion changes

src/app/shared/helper-services/analysis-validation.service.ts
=> fix validation for skipped groups

src/app/calculations/calanderization/calanderizeMeters.ts, src/app/calculations/conversions/convertMeterData.ts, src/app/facility/utility-data/calanderization/calanderization.component.ts
=> fix conversion of volume

src/app/account/account-analysis/account-analysis-results/account-analysis-facilities-summary/account-analysis-facilities-summary.component.html, src/app/account/account-analysis/account-analysis-results/account-analysis-facilities-summary/account-analysis-facilities-summary.component.spec.ts, src/app/account/account-analysis/account-analysis-results/account-analysis-facilities-summary/account-analysis-facilities-summary.component.ts, src/app/account/account-analysis/account-analysis-results/account-analysis-results.component.html, src/app/account/account-analysis/account-analysis-results/account-analysis-results.component.ts, src/app/account/account-analysis/account-analysis-results/annual-account-analysis/annual-account-analysis.component.ts, src/app/account/account-analysis/account-analysis.module.ts, src/app/account/account-analysis/account-analysis.service.ts, src/app/calculations/analysis-calculations/annualAccountAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/routing/account.routes.ts, src/app/shared/shared-analysis/monthly-analysis-summary-graph/monthly-analysis-summary-graph.component.ts, src/app/web-workers/annual-account-analysis.worker.ts
=> Add tab with facilities monthly performance to account analysis

package.json, src/app/account/account-reports/better-plants-report/primary-energy-consumption-table/primary-energy-consumption-table.component.html, src/app/shared/shared-analysis/monthly-analysis-summary-graph/monthly-analysis-summary-graph.component.ts
hotfix: add percent savings to facility summaries in account analysis
hotfix: report year diesel value in BP report
update version number
connects #1293
=> Updates for release v0.10.2

src/app/facility/analysis/run-analysis/group-analysis/monthly-analysis-summary/monthly-analysis-summary.component.ts, src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
connects #1202 
fixes SEP validation and labels on model inspection graph
=> fixes to SEP validation

src/app/account/account-reports/account-report-setup/better-plants-setup/better-plants-setup.component.html, src/app/account/account-reports/account-reports.service.ts, src/app/account/account-reports/better-plants-report/better-plants-report.component.html, src/app/account/account-reports/better-plants-report/better-plants-report.component.ts, src/app/account/account-reports/better-plants-report/primary-energy-consumption-table/primary-energy-consumption-table.component.html, src/app/account/account-reports/better-plants-report/primary-water-consumption-table/primary-water-consumption-table.component.html, src/app/calculations/better-plants-calculations/betterPlantsReportClass.ts, src/app/models/overview-report.ts, src/app/web-workers/better-plants-report.worker.ts
=> generate BP report for all years between baseline and report year

src/app/account/account-settings/account-settings.component.html, src/app/account/account-settings/account-settings.component.ts, src/app/core-components/manage-accounts/manage-accounts.component.html, src/app/core-components/manage-accounts/manage-accounts.component.ts, src/app/indexedDB/account-analysis-db.service.ts, src/app/indexedDB/account-report-db.service.ts, src/app/indexedDB/analysis-db.service.ts, src/app/indexedDB/custom-emissions-db.service.ts, src/app/indexedDB/db-changes.service.ts, src/app/indexedDB/facility-db.service.ts, src/app/indexedDB/predictors-db.service.ts, src/app/indexedDB/utilityMeter-db.service.ts, src/app/indexedDB/utilityMeterData-db.service.ts, src/app/indexedDB/utilityMeterGroup-db.service.ts
=> enhanced messaging for bulk delete

src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> fix regression data bug for volume energy meters

src/app/calculations/emissions-calculations/emissions.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.ts
=> don't overwrite energy use for emissions

src/app/calculations/better-plants-calculations/betterPlantsReportClass.ts
=> fix intermittent year values for new facilities BP reports

src/app/calculations/calanderization/calanderizeMeters.ts, src/app/indexedDB/predictors-db.service.ts, src/app/indexedDB/utilityMeterData-db.service.ts
connects 1301
hotfix: calendarize by month issue for February
=> meter data and predictor messages by 25

package-lock.json, package.json
=> updates version number for release

src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.html
=> fix dropdown true/false for production predictor form

src/app/account/custom-database/regional-emissions-data/emissions-data-dashboard/emissions-data-dashboard.component.html, src/app/account/custom-database/regional-emissions-data/emissions-data-form/emissions-data-form.component.html, src/app/calculations/emissions-calculations/emissions.ts, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/general-utility-data-table/general-utility-data-table.component.html, src/app/shared/data-overview/facilities-usage-stacked-bar-chart/facilities-usage-stacked-bar-chart.component.ts, src/app/shared/data-overview/facilities-usage-table/facilities-usage-table.component.html, src/app/shared/data-overview/facility-usage-donut/facility-usage-donut.component.ts, src/app/shared/data-overview/meter-usage-donut/meter-usage-donut.component.ts, src/app/shared/data-overview/meter-usage-table/meter-usage-table.component.html, src/app/shared/data-overview/meters-overview-stacked-line-chart/meters-overview-stacked-line-chart.component.ts, src/app/shared/data-overview/monthly-utility-usage-line-chart/monthly-utility-usage-line-chart.component.ts, src/app/shared/data-overview/utilities-usage-chart/utilities-usage-chart.component.ts, src/app/shared/data-overview/utility-consumption-table/emissions-consumption-table/emissions-consumption-table.component.html
=> display all emissions values in tonne instead of kg

src/app/shared/helper-services/export-to-excel-template.service.ts
=> exporting meters to excel using correct water type in fuel column

src/app/calculations/calanderization/calanderizeMeters.ts
=> set NaN to zero in calendarization math

src/app/calculations/dashboard-calculations/accountOverviewClass.ts, src/app/calculations/dashboard-calculations/facilityOverviewClass.ts, src/app/shared/data-overview/meters-overview-stacked-line-chart/meters-overview-stacked-line-chart.component.ts
=> set monthly usage to 0 for meters not included in energy

src/app/account/account-reports/account-reports-dashboard/account-reports-item-card/account-reports-item-card.component.html, src/app/indexedDB/account-analysis-db.service.ts, src/app/shared/helper-pipes/analysis-category.pipe.spec.ts, src/app/shared/helper-pipes/analysis-category.pipe.ts, src/app/shared/helper-pipes/helper-pipes.module.ts
=> add type label to report cards for water or energy

.gitignore, src/app/core-components/electron-update/electron-update.component.css, src/app/core-components/electron-update/electron-update.component.html, src/app/core-components/electron-update/electron-update.component.ts, src/app/core-components/header/header.component.html, src/app/core-components/header/header.component.ts, src/app/core-components/loading/loading.component.ts, src/app/static-content/feedback/feedback.component.html
=> handle errors on update and update feedback page with link to github

src/app/calculations/performance-report-calculations/performanceReport.ts
=> fix bug with skipped groups in performance report

src/app/account/account-reports/account-report-setup/better-climate-setup/better-climate-setup.component.html, src/app/account/account-reports/account-report-setup/better-climate-setup/better-climate-setup.component.ts, src/app/account/account-reports/account-reports.service.ts, src/app/account/account-reports/better-climate-report/absolute-emissions-table/absolute-emissions-table.component.css, src/app/account/account-reports/better-climate-report/absolute-emissions-table/absolute-emissions-table.component.html, src/app/account/account-reports/better-climate-report/annual-facility-climate-summary-table/annual-facility-climate-summary-table.component.html, src/app/account/account-reports/better-climate-report/annual-facility-climate-summary-table/annual-facility-climate-summary-table.component.ts, src/app/account/account-reports/better-climate-report/better-climate-report.component.html, src/app/account/account-reports/better-climate-report/better-climate-report.component.ts, src/app/indexedDB/account-report-db.service.ts, src/app/models/overview-report.ts, src/app/weather-data/weather-stations/weather-stations-map/weather-stations-map.component.ts
connects #1359
adds validation to climate report setup
adds more options for report content
=> update validation for climate report setup

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts
=> direct connection true for on site generation

src/app/analytics/analytics.service.ts
=> move isVerifi boolean out of analytics payload

package-lock.json, package.json
=> update version number in package

.github/workflows/main.yml, .github/workflows/web.yml
- Commented out conditional used to execute electron (no tag required)
- Reordered web deployment statements
=> Added fixes to pipeline

.github/workflows/main.yml, .github/workflows/web.yml
Also removed unnecessary `chgrp` statement.
=> Add secret inheritance for Electron workflow

src/app/account/account-home/account-home.component.ts, src/app/account/account-overview/account-overview.component.ts
=> add fallback for missing webworkers for account overview

src/app/shared/helper-services/backup-data.service.ts
=> importing and exporting custom db items working

src/app/shared/helper-services/backup-data.service.ts
=> fix backup data service

src/app/account/custom-database/custom-fuel-data/custom-fuel-data-form/custom-fuel-data-form.component.ts, src/app/calculations/conversions/convertMeterData.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.ts, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.service.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-utility-bill/edit-utility-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-utility-bill/edit-utility-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-vehicle-meter-bill/edit-vehicle-meter-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-vehicle-meter-bill/edit-vehicle-meter-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/general-utility-data-table/general-utility-data-table.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/indexedDB/utilityMeterData-db.service.ts, src/app/models/idb.ts, src/app/shared/sharedHelperFuntions.ts, src/app/upload-data/data-setup/file-setup/confirm-and-submit/confirm-and-submit.component.ts, src/app/upload-data/data-setup/file-setup/confirm-readings/confirm-readings.component.ts, src/app/upload-data/upload-data-v1.service.ts, src/app/upload-data/upload-data-v2.service.ts, src/app/upload-data/upload-data.service.ts
connects #1389 
Adds ability to alter the heat capacity or fuel efficiency in the monthly billing page.
=> Set heat capacity or fuel efficiency by month

src/app/facility/visualization/correlation-plot-menu/correlation-plot-menu.component.html, src/app/facility/visualization/correlation-plot-menu/correlation-plot-menu.component.ts, src/app/facility/visualization/time-series/time-series.component.ts, src/app/facility/visualization/visualization-state.service.ts
=> add total energy to visualization plots

src/app/account/account-analysis/account-analysis-dashboard/account-analysis-item-card/account-analysis-item-card.component.ts, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/account/account-home/account-energy-card/account-energy-reduction-goal/account-energy-reduction-goal.component.ts, src/app/account/account-home/account-water-card/account-water-reduction-goal/account-water-reduction-goal.component.ts, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.ts, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.html, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.ts, src/app/facility/facility-home/facility-energy-card/facility-energy-reduction-goal/facility-energy-reduction-goal.component.ts, src/app/facility/facility-home/facility-water-card/facility-water-reduction-goal/facility-water-reduction-goal.component.ts
connects #1371 
also disabled options for analysis when facility analysis item is used inside of an account analysis
=> Required baseline year to match goals for analysis progress towards goals

src/app/calculations/emissions-calculations/emissions.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-vehicle-meter-bill/edit-vehicle-meter-bill.component.html, src/app/upload-data/upload-data-v2.service.ts
connects #1387 
Fixes mobile emissions calculations 
Fixes heat capacity being set for vehicles on import
=>  Fixes to mobile emissions calculations

src/app/upload-data/upload-data-shared-functions.service.ts, src/app/upload-data/upload-data-v1.service.ts, src/app/upload-data/upload-data-v2.service.ts
connects #1171 
connects #1405
=> fix create new groups on upload

src/app/calculations/emissions-calculations/emissions.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/other-emissions-data-table/other-emissions-data-table.component.ts, src/app/shared/data-overview/emissions-stacked-line-chart/emissions-stacked-line-chart.component.ts
Additional fixes for bugs found when uploading example template data
connects #1171
=> Template emissions upload fixes

src/app/account/account-overview/water-overview/water-overview.component.html, src/app/account/account-reports/data-overview-report/data-overview-account-report/account-section-report/account-section-report.component.html, src/app/account/account-reports/data-overview-report/data-overview-facility-report/facility-section-report/facility-section-report.component.html, src/app/calculations/dashboard-calculations/accountOverviewClass.ts, src/app/shared/data-overview/account-utility-usage-table/account-utility-usage-table.component.html, src/app/shared/data-overview/account-water-stacked-bar-chart/account-water-stacked-bar-chart.component.html, src/app/shared/data-overview/account-water-stacked-bar-chart/account-water-stacked-bar-chart.component.spec.ts, src/app/shared/data-overview/account-water-stacked-bar-chart/account-water-stacked-bar-chart.component.ts, src/app/shared/data-overview/account-water-usage-donut/account-water-usage-donut.component.html, src/app/shared/data-overview/account-water-usage-donut/account-water-usage-donut.component.spec.ts, src/app/shared/data-overview/account-water-usage-donut/account-water-usage-donut.component.ts, src/app/shared/data-overview/account-water-usage-table/account-water-usage-table.component.css, src/app/shared/data-overview/account-water-usage-table/account-water-usage-table.component.html, src/app/shared/data-overview/account-water-usage-table/account-water-usage-table.component.spec.ts, src/app/shared/data-overview/account-water-usage-table/account-water-usage-table.component.ts, src/app/shared/data-overview/data-overview.module.ts, src/app/shared/data-overview/facilities-usage-stacked-bar-chart/facilities-usage-stacked-bar-chart.component.ts, src/app/shared/utilityColors.ts
connects #1203 
add components and logic to update account overview pages with breakdown of water intake/discharge by type
=> Update account overview with water types

src/app/shared/helper-services/energy-units-helper.service.ts, src/app/upload-data/upload-data.service.ts
connects #953 
clean up unused code in upload service
=> Add NG and Elec to check for source type on upload

src/app/calculations/conversions/convertMeterData.ts, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.html, src/app/upload-data/data-setup/file-setup/manage-meters/manage-meters.component.ts
connects #1428 
select from existing meters in edit meter page of import if its flagged as a new meter.
=> add ability to import to existing facility meter

.github/workflows/electron.yml, .github/workflows/main.yml, .github/workflows/web.yml
- Updated deployment runner labels used to `prod` and `dev`
- Added job to deploy builds to development environment if merging into `develop` branch
=> Updated workflow files - added dev env deploy job, updated runner labels

src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/account/account-analysis/account-analysis.module.ts, src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.ts, src/app/account/account-reports/account-report-setup/better-plants-setup/better-plants-setup.component.html, src/app/account/account-reports/account-report-setup/performance-setup/performance-setup.component.html, src/app/account/account-reports/better-plants-report/better-plants-report.component.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts, src/app/facility/analysis/analysis.module.ts, src/app/facility/analysis/analysis.service.ts, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/edit-meter-form.component.html, src/app/indexedDB/account-analysis-db.service.ts, src/app/indexedDB/analysis-db.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/analysis.ts, src/app/models/idb.ts, src/app/shared/label-with-tooltip/label-with-tooltip.component.html, src/app/shared/label-with-tooltip/label-with-tooltip.component.ts, src/app/shared/label-with-tooltip/labelTooltips.ts, src/app/shared/settings-forms/general-information-form/general-information-form.component.html, src/app/upload-data/data-setup/file-setup/select-worksheet/select-worksheet.component.html
=> UI updates for baseline adjustment changes

src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/account/account-reports/better-plants-report/better-plants-report.component.ts, src/app/account/account-reports/better-plants-report/primary-water-consumption-table/primary-water-consumption-table.component.html, src/app/account/account-reports/excel-writer-services/better-plants-excel-writer.service.ts, src/app/calculations/analysis-calculations/annualAccountAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/annualFacilityAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualGroupAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyGroupAnalysisClass.ts, src/app/facility/analysis/analysis.service.ts, src/app/facility/analysis/run-analysis/group-analysis/annual-analysis-summary/annual-analysis-summary.component.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/indexedDB/account-analysis-db.service.ts, src/app/indexedDB/analysis-db.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/analysis.ts, src/app/models/idb.ts, src/app/shared/shared-analysis/analysis-summary-table-filter/analysis-summary-table-filter.component.html, src/app/shared/shared-analysis/annual-analysis-summary-table/annual-analysis-summary-table.component.html, src/app/shared/shared-analysis/annual-analysis-summary-table/annual-analysis-summary-table.component.ts, src/app/shared/shared-analysis/monthly-analysis-summary-table/monthly-analysis-summary-table.component.html, src/app/shared/shared-analysis/monthly-analysis-summary-table/monthly-analysis-summary-table.component.ts
connects #1226 
remove baseline adjustment for normalization math.
Updated math using new methods from @koay9f  and Chris Price
.
=> Update math for adjustments

.github/workflows/web.yml
Please see: https://github.com/ORNL-AMO/VERIFI/issues/1448
=> Issue 1448 - append commit hash to package.json build version

src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/account/account-reports/better-plants-report/better-plants-report.component.ts, src/app/account/account-reports/better-plants-report/primary-energy-consumption-table/primary-energy-consumption-table.component.html, src/app/account/account-reports/excel-writer-services/better-plants-excel-writer.service.ts, src/app/calculations/analysis-calculations/annualAccountAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/annualFacilityAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualGroupAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisDataClass.ts, src/app/calculations/better-plants-calculations/betterPlantsReportClass.ts, src/app/facility/analysis/analysis.service.ts, src/app/facility/analysis/run-analysis/group-analysis/annual-analysis-summary/annual-analysis-summary.component.ts, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html, src/app/indexedDB/account-analysis-db.service.ts, src/app/indexedDB/analysis-db.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/analysis.ts, src/app/models/idb.ts, src/app/shared/shared-analysis/annual-analysis-summary-table/annual-analysis-summary-table.component.html, src/app/shared/shared-analysis/annual-analysis-summary-table/annual-analysis-summary-table.component.ts, src/app/shared/shared-analysis/monthly-analysis-summary-table/monthly-analysis-summary-table.component.html, src/app/shared/shared-analysis/monthly-analysis-summary-table/monthly-analysis-summary-table.component.ts
connects #1226 
Updates to adjustment math. Need test data
=> Updates to adjustment math.

src/app/upload-data/upload-data-v2.service.ts
=> parse heating value for data point from template

src/app/shared/helper-services/export-to-excel-template.service.ts
=> fix export to template for efficiency and heating value

src/app/shared/helper-services/export-to-excel-template.service.ts
=> fix export fuel efficiency

src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html
=> fix baseline adjustment UI in account

src/app/calculations/analysis-calculations/annualAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClass.ts
=> update math to use baselineModeledEnergyUse

src/app/shared/helper-services/energy-units-helper.service.ts
=> fix parsing NG to natural gas

src/app/calculations/calanderization/calanderizeMeters.ts, src/app/calculations/emissions-calculations/emissions.ts
=> Subtract excess recs from market electricity

src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-vehicle-meter-bill/edit-vehicle-meter-bill.component.ts
=> fix biofuel issues

src/app/account/account-home/account-home.component.ts, src/app/facility/facility-home/facility-home.component.ts, src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-filter/utility-meter-data-filter.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/electricity-data-table/electricity-data-table.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/models/meterDataFilter.ts
connects #1171 
updated example from Kristina
Quick fixes from release review from Paulomi
Fixes for home screen progress bar
=> Updated Example and Release Review Fixes

src/app/account/account-analysis/select-facility-analysis-items/select-item-table/select-item-table.component.html, src/app/facility/analysis/run-analysis/group-analysis/group-analysis-options/group-analysis-options.component.html
=> Exclude from Analysis verbage change

src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.css, src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.html
=> new facility checkbox larger and bold

src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.html, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
connects #1486 
gives popup to change report year
updates model validation notes of models when report year changes
=> Workflow for changing report year for analysis items

src/app/shared/data-overview/facilities-usage-table/facilities-usage-table.component.ts
=> quick fix account overview facility emissions table ordering

src/app/account/account-reports/print-report-button/print-report-button.component.css, src/app/account/account-reports/print-report-button/print-report-button.component.html
=> add hover text to report buttons

src/app/calculations/analysis-calculations/annualAccountAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/annualFacilityAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/annualGroupAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/groupMonthlyAnalysisCalculatedValuesClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClassSummation.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisDataClass.ts, src/app/models/analysis.ts
=> use summations for all non group results in analysis

src/app/calculations/analysis-calculations/groupMonthlyAnalysisCalculatedValuesClass.ts, src/app/calculations/analysis-calculations/monthlyAccountAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClassSummation.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts, src/app/calculations/analysis-calculations/monthlyFacilityAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyGroupAnalysisClass.ts
=> add baseline adjustment for new facilities logic

src/app/calculations/analysis-calculations/monthlyAccountAnalysisDataClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClassSummation.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts
=> fixes for adjusted for new facilities

src/app/calculations/analysis-calculations/groupMonthlyAnalysisCalculatedValuesClass.ts
=> updated calculations to handle 0 energy use for a given month

src/app/upload-data/data-setup/file-setup/confirm-predictors/confirm-predictors.component.ts, src/app/upload-data/upload-data-shared-functions.service.ts, src/app/upload-data/upload-data-v1.service.ts, src/app/upload-data/upload-data-v2.service.ts, src/app/upload-data/upload-data.service.ts
=> fixes to upload predictor data to calculate new degree days

src/app/calculations/analysis-calculations/groupMonthlyAnalysisCalculatedValuesClass.ts
=> updated math to handle energy use = 0

src/app/calculations/analysis-calculations/groupMonthlyAnalysisCalculatedValuesClass.ts
=> further changes to baselineAdjustmentForOtherV2 math

src/app/calculations/analysis-calculations/annualAnalysisSummaryDataClass.ts
=> SEnPI calculated in account

package.json
=> updated to v0.11.2-beta

src/app/upload-data/upload-data-shared-functions.service.ts, src/app/upload-data/upload-data-v1.service.ts, src/app/upload-data/upload-data.service.ts
=> fixes to uploading new predictors into existing predictor data

src/app/upload-data/upload-data-v1.service.ts, src/app/upload-data/upload-data.service.ts
connects #1522 
This fixes a bug when importing using v1 of the template from the setup wizard. It needed to use the account in the setup wizard not the selected account
=> quick fix to importing using old template

src/app/weather-data/monthly-station-data/monthly-station-graph/monthly-station-graph.component.ts
connects #1549 
range set to first of month and first day of next month
=> set range for x axis of monthly weather data

src/app/facility/utility-data/predictor-data/manage-predictors/predictors-table/predictors-table.component.ts, src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.html, src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.ts, src/app/facility/utility-data/predictor-data/predictor-entries/predictor-entries-table/predictor-entries-table.component.html, src/app/facility/utility-data/predictor-data/predictor-entries/predictor-entries-table/predictor-entries-table.component.ts, src/app/models/idb.ts, src/app/weather-data/weather-data.component.ts, src/app/weather-data/weather-data.service.ts, src/app/weather-data/weather-stations/weather-stations.component.ts
manually set weather data when there are errors in calculations.
fixes to navigation to weather data pages from predictors to start on facility
connects #1548
=> issue 1548: Manually set weather data

src/app/setup-wizard/setup-welcome/setup-welcome.component.html, src/app/setup-wizard/setup-welcome/setup-welcome.component.ts
=> add modal for load example

src/app/calculations/better-plants-calculations/betterPlantsReportClass.ts
=> convert results of bp reports for correct units

src/app/account/account-banner/account-banner.component.html, src/app/core-components/sidebar/sidebar.component.html, src/app/facility/facility-banner/facility-banner.component.html
=> Updated Hover Labels for Facility/Account Tabs and Sidebar

src/app/facility/visualization/visualization.component.ts
=> fixes to initializing visualization when changing facilities

src/app/indexedDB/update-db-entry.service.ts, src/app/upload-data/upload-data.service.ts
=> fix upload wizard name bug

src/app/upload-data/data-setup/file-setup/confirm-and-submit/confirm-and-submit.component.ts
=> meter data should only skip existing and not new

src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.ts, src/app/shared/helper-services/degree-days.service.ts
connects #1548 
Needed to set degree day month calculations first entry to the first day of the month.
=> month degree day calcs start on first day of the month

src/app/upload-data/upload-data.service.ts
=> fix submit meter causing parsing meter data error

package.json
=> update to v0.11.3-beta

src/app/account/account-reports/excel-writer-services/better-climate-excel-writer.service.ts
connects #1584
wrong data mapped to excel export
=> fix BCC reporting invalid cell data

src/app/calculations/conversions/definitions/mass.ts, src/app/shared/unitOptions.ts
=> add short ton option and update long ton

src/app/account/account-reports/account-report-setup/better-plants-setup/better-plants-setup.component.html, src/app/account/account-reports/account-reports.service.ts, src/app/account/account-reports/better-plants-report/better-plants-report.component.html, src/app/app.component.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/overview-report.ts
=> add include performance table option to better plants report

src/app/weather-data/weather-data.component.ts
=> update generated hdd and cdd names with temp threshold

src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.html, src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.ts
=> save and add another functionality added to predictor entries

src/app/upload-data/upload-data-v1.service.ts, src/app/upload-data/upload-data.service.ts
=> update meter number to be more meaningful on upload from excel

src/app/account/custom-database/regional-emissions-data/emissions-data-dashboard/emissions-data-dashboard.component.html, src/app/account/custom-database/regional-emissions-data/emissions-data-form/emissions-data-form.component.html
=> update custom emissions with kg CO2 label instead of tonne

src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.html, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.ts, src/app/facility/utility-data/calanderization/calanderization.component.html, src/app/facility/utility-data/calanderization/calanderization.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.component.ts, src/app/shared/data-overview/emissions-stacked-line-chart/emissions-stacked-line-chart.component.ts, src/app/shared/helper-pipes/helper-pipes.module.ts, src/app/shared/helper-pipes/meter-source-color.pipe.spec.ts, src/app/shared/helper-pipes/meter-source-color.pipe.ts
=> use pipe for background color label of source

src/app/account/custom-database/custom-fuel-data/custom-fuel-data-form/existing-fuels-modal/existing-fuels-modal.component.html, src/app/account/custom-database/custom-fuel-data/custom-fuel-data-form/existing-fuels-modal/existing-fuels-modal.component.ts
=> update fuel options tables in custom emissions with units

src/app/account/account-reports/account-report-setup/better-climate-setup/better-climate-setup.component.css, src/app/account/account-reports/account-report-setup/better-climate-setup/better-climate-setup.component.html, src/app/account/account-reports/account-report-setup/better-climate-setup/better-climate-setup.component.ts, src/app/account/account-reports/better-climate-report/better-climate-report.component.ts, src/app/app.component.ts, src/app/calculations/carbon-calculations/betterClimateReport.ts, src/app/facility/utility-data/meter-grouping/meter-grouping.component.ts, src/app/indexedDB/account-report-db.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/overview-report.ts, src/app/web-workers/better-climate-report.worker.ts
connects #1602 
Can select which facilities and meter groups to include in the report. Can also select to include all data as default
=> Add select groups or facilities to include in BCC report

src/app/account/custom-database/custom-fuel-data/custom-fuel-data-form/existing-fuels-modal/existing-fuels-modal.component.html
=> fix label in table for custom emissions

src/app/indexedDB/update-db-entry.service.ts, src/app/shared/unitOptions.ts
=> update dtherms option to match template, update old meters

src/app/facility/utility-data/energy-consumption/energy-source/edit-meter-form/emissions-details-table/emissions-details-table.component.html
=> fix unit label for other fuels emissions table

src/app/shared/fuel-options/stationaryGasOptions.ts, src/app/shared/fuel-options/stationaryLiquidOptions.ts, src/app/shared/fuel-options/stationarySolidOptions.ts
=> updated emissions factors from excel table

src/app/account/account-reports/excel-writer-services/better-climate-excel-writer.service.ts, src/app/calculations/emissions-calculations/emissions.ts, src/app/shared/fuel-options/stationaryGasOptions.ts
=> add Renewable Natural Gas and Hydrogen for stationary

src/app/calculations/conversions/definitions/energy.ts
connects #1613 
DTherm definition missing for new label that was changed to match template
=> fix DTherm calculation bug

package.json
=> update version v0.11.5-beta

src/app/account/account-reports/better-plants-report/primary-water-consumption-table/primary-water-consumption-table.component.html
connects #1639 
Added fields to BP report for water to match BP report for energy. Fields added in VERIFI version, not in excel version.
=> update water BP report with missing adjustment and savings data

src/app/calculations/analysis-calculations/groupMonthlyAnalysisCalculatedValuesClass.ts
=> fix math issue for 0 in analysis

package-lock.json, package.json
=> updated to v0.11.6-beta

package.json
=> update version number for v0.11.7-beta hotfix release

src/app/core-components/electron-update/electron-update.component.css
=> make close button more visibile on auto-update notification

src/app/core-components/sidebar/sidebar.component.html, src/app/routing/app-routing.module.ts, src/app/static-content/about/about.component.html, src/app/static-content/privacy-notice/privacy-notice.component.css, src/app/static-content/privacy-notice/privacy-notice.component.html, src/app/static-content/privacy-notice/privacy-notice.component.spec.ts, src/app/static-content/privacy-notice/privacy-notice.component.ts, src/app/static-content/static-content.module.ts
connects #1660 
connects #1661 
added privacy policy page
updated about page with data policy
=> About and Privacy page updates

src/app/account/account-reports/better-plants-report/company-information-table/company-information-table.component.html, src/app/account/account-reports/better-plants-report/company-information-table/company-information-table.component.ts, src/app/account/account-reports/data-overview-report/data-overview-account-report/account-title-page/account-title-page.component.html, src/app/account/account-reports/data-overview-report/data-overview-account-report/account-title-page/account-title-page.component.ts, src/app/account/account-reports/data-overview-report/data-overview-facility-report/facility-title-page/facility-title-page.component.html, src/app/account/account-reports/data-overview-report/data-overview-facility-report/facility-title-page/facility-title-page.component.ts, src/app/account/account-settings/account-settings.component.html, src/app/account/account-settings/account-settings.component.ts, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.html, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.ts, src/app/shared/form-data/naics-data.ts, src/app/shared/helper-pipes/helper-pipes.module.ts, src/app/shared/helper-pipes/naics-display.pipe.spec.ts, src/app/shared/helper-pipes/naics-display.pipe.ts, src/app/shared/settings-forms/general-information-form/general-information-form.component.ts
=> updated NAICS display logic in table

src/app/calculations/carbon-calculations/betterClimateYearsDetails.ts, src/app/calculations/conversions/convertMeterData.ts
connects #1666 
fixes site to source issue in report.
updates math for included meters in different sections from kristina.
=> BCC Quick Fixes

src/app/account/custom-database/regional-emissions-data/emissions-data-form/emissions-data-form.component.ts
=> fix emissions factors year options hard coded to max 2022

src/app/facility/utility-data/calanderization/calanderized-meter-data-table/calanderized-meter-data-table.component.html
=> fix monthly table columns displayed

src/app/account/account-reports/account-report-setup/better-climate-setup/better-climate-setup.component.html, src/app/account/account-reports/account-report-setup/better-climate-setup/better-climate-setup.component.ts, src/app/calculations/carbon-calculations/betterClimateYearsDetails.ts, src/app/shared/helper-services/backup-data.service.ts
=> Fixes to remaining electricity calc in BCC report

src/app/calculations/carbon-calculations/betterClimateYearsDetails.ts
=> fix for total electricity calc

package-lock.json, package.json
=> update to v0.11.8-beta for release

src/app/account/account-reports/better-plants-report/primary-energy-consumption-table/primary-energy-consumption-table.component.ts, src/app/account/account-reports/better-plants-report/primary-water-consumption-table/primary-water-consumption-table.component.ts
=> fix fiscal year label for BP reports

src/app/account/account-reports/account-report-setup/data-overview-setup/data-overview-setup.component.css, src/app/account/account-reports/account-report-setup/data-overview-setup/data-overview-setup.component.html, src/app/account/account-reports/data-overview-report/data-overview-report.component.ts, src/app/account/account-settings/account-settings.component.ts, src/app/facility/utility-data/meter-grouping/edit-meter-group-form/edit-meter-group-form.component.ts, src/app/indexedDB/account-report-db.service.ts, src/app/indexedDB/update-db-entry.service.ts, src/app/models/idbModels/accountReport.ts, src/app/models/overview-report.ts, src/app/shared/helper-services/backup-data.service.ts
=> add ability to select groups for data overview report

src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts
=> Add ability to bulk create analysis in accounts analysis

src/app/facility/utility-data/utility-banner/utility-banner.component.html, src/app/facility/utility-data/utility-banner/utility-banner.component.ts, src/app/upload-data/data-setup/file-setup/confirm-and-submit/confirm-and-submit.component.ts, src/app/upload-data/data-setup/file-setup/confirm-predictors/confirm-predictors.component.ts, src/app/upload-data/data-setup/file-setup/set-facility-predictors/set-facility-predictors.component.ts, src/app/upload-data/upload-data-shared-functions.service.ts, src/app/upload-data/upload-data-v1.service.ts, src/app/upload-data/upload-data-v2.service.ts, src/app/upload-data/upload-data.service.ts
connects #1668 
fixes import for predictors both from template and using wizard.
Import broke when changes were made for the "Treating predictors like meters" issue.
=> Update predictor import logic.

src/app/facility/visualization/visualization-state.service.ts
=> fix date bug in visualization

src/app/facility/utility-data/predictors/predictors-data/predictors-data-form/predictors-data-form.component.html, src/app/shared/helper-services/backup-data.service.ts
connects #1686 
Hotfix import predictors date bug for timestamps
=> Add ability to override all calculated weather predictors

src/app/shared/helper-services/degree-days.service.ts
=> add error check for gaps at end of month data readings

src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.css, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.html, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.spec.ts, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.ts, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/order-calculated-predictor-data.pipe.spec.ts, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/order-calculated-predictor-data.pipe.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-form/predictors-data-form.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/order-predictor-data-table.pipe.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.html, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors.module.ts, src/app/routing/facility.routes.ts
connects #1326 
Adds page to update weather data by selecting date ranges
=> Weather Data Bulk Update Page

src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.html, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts
=> add ability to copy predictors to other facilities

src/app/shared/helper-services/export-to-excel-template.service.ts
=> fixes to predictors export to template

src/app/calculations/analysis-calculations/groupMonthlyAnalysisCalculatedValuesClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClassSummation.ts
connects #1720 
apply banking calcs on savings
=> updated savings calculations for banking

package-lock.json, package.json, src/app/app.component.ts, src/app/core-components/toast-notifications/toast-notifications.service.ts, src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.html, src/app/facility/utility-data/predictor-data/manage-predictors/edit-predictor/edit-predictor.component.ts, src/app/facility/utility-data/predictor-data/manage-predictors/predictors-table/predictors-table.component.ts, src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.html, src/app/facility/utility-data/predictor-data/predictor-entries/edit-predictor-entry/edit-predictor-entry.component.ts, src/app/facility/utility-data/predictor-data/predictor-entries/predictor-entries-table/predictor-entries-table.component.ts, src/app/indexedDB/predictors-db.service.ts, src/app/shared/helper-services/degree-days.service.ts, src/app/upload-data/upload-data.service.ts, src/app/weather-data/annual-station-data/annual-station-data.component.ts, src/app/weather-data/monthly-station-data/monthly-station-data.component.html, src/app/weather-data/monthly-station-data/monthly-station-data.component.ts, src/app/weather-data/weather-data.component.html, src/app/weather-data/weather-data.component.ts
Weather data servers are down and we needed to add error handling around weather data. 
connects #1734
=> Patch Release: v0.11.9-beta

src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.css, src/app/facility/analysis/analysis-dashboard/analysis-item-card/analysis-item-card.component.html
=> Issue 1711: add site/source tag to analysis cards

src/app/facility/facility-reports/facility-report-setup/facility-analysis-report-setup/facility-analysis-report-setup.component.ts
=> fix table column category toggle

src/app/shared/helper-services/degree-days.service.ts
=> filter missing dry bulb temp values

src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.css, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.html, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/order-predictor-data-table.pipe.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.html, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.html, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.css, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.html, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts, src/app/facility/utility-data/predictors/predictors.component.html, src/app/facility/utility-data/predictors/predictors.component.ts, src/app/facility/utility-data/predictors/predictors.module.ts, src/app/facility/utility-data/utility-banner/utility-banner.component.css, src/app/facility/utility-data/utility-banner/utility-banner.component.html, src/app/facility/utility-data/utility-banner/utility-banner.component.ts, src/app/help-panel/weather-data-help/annual-station-help/annual-station-help.component.html, src/app/help-panel/weather-data-help/daily-station-help/daily-station-help.component.html, src/app/help-panel/weather-data-help/monthly-station-help/monthly-station-help.component.html, src/app/help-panel/weather-data-help/weather-data-help.component.html, src/app/help-panel/weather-data-help/weather-stations-help/weather-stations-help.component.html, src/app/models/idbModels/utilityMeterData.ts, src/app/shared/helper-services/predictor-data-helper.service.spec.ts, src/app/shared/helper-services/predictor-data-helper.service.ts, src/app/shared/label-with-tooltip/labelTooltips.ts, src/app/weather-data/annual-station-data/annual-station-data.component.html, src/app/weather-data/weather-data.component.html
connects #1723 
- Updates language from "degree days" to "weather" for help/buttons
- Adds messaging for predictors that have fallen behind meter data entries
- Creates predictor data on creation of predictors when applicable
=> Issue 1723: Predictor updates after feedback

src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.html, src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.ts
=> update workflow for bulk updates in weather data predictors

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.html, src/app/shared/shared-reports/facility-analysis-report/group-analysis-report/regression-model-details/regression-model-details.component.html
=> remove SEP from labels for model validation

src/app/shared/helper-services/backup-data.service.ts
=>  fix importing backup with banking

src/app/shared/helper-pipes/custom-number.pipe.ts
=> round display values smaller than .00001 to 0

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-inspection/regression-model-inspection.component.ts
=> fixes to model inspection

package-lock.json, package.json
=> update version number and vulnerabilities

src/app/shared/helper-pipes/degree-day-total.pipe.ts, src/app/shared/helper-services/backup-data.service.ts, src/app/shared/helper-services/degree-days.service.ts, src/app/weather-data/monthly-station-data/monthly-station-data.component.html, src/app/weather-data/monthly-station-data/monthly-station-table/monthly-station-table.component.html
#1587 
Quick fixes to weather data tables and summations
Quick fixes to importing predictor data date
=> Weather data fixes

src/app/calculations/calanderization/calanderizeMeters.ts
=> fix utility costs calanderization

src/app/account/account-reports/account-report-setup/performance-setup/performance-setup.component.ts
=> allow source performance reports

package.json
=> fix build script command

src/app/shared/helper-services/survey.service.ts, src/app/shared/user-survey/user-survey.component.html, src/app/shared/user-survey/user-survey.component.ts
=> updated logic for survey modal

src/app/account/account-home/account-home-summary/account-home-summary.component.html, src/app/app.component.ts, src/app/facility/facility-home/facility-home-summary/facility-home-summary.component.html
connects #1790 
updated fontawesome dependency fix
=> fix fontawesome exclamation point

src/environments/environment.dev-srv.ts
=> fix environment vars with weather data api

src/app/calculations/analysis-calculations/groupMonthlyAnalysisRollupValuesClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts
=> rolling baseline adjustment for other

src/app/shared/shared-analysis/analysis-summary-table-filter/analysis-summary-table-filter.component.ts
=> fix bug with predictors using id instead of guid

src/app/calculations/analysis-calculations/groupMonthlyAnalysisRollupValuesClass.ts, src/app/calculations/analysis-calculations/monthlyAnalysisSummaryDataClass.ts
=> fix to bp adjustment

src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.css, src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.html, src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.ts, src/app/facility/analysis/analysis-footer/analysis-footer.component.css, src/app/facility/analysis/analysis-footer/analysis-footer.component.html
=> Issue 1808: add analysis name in footer of analysis

src/app/calculations/analysis-calculations/monthlyAnalysisCalculatedValuesClassSummation.ts
=> fix facility baseline adjustment

src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.css, src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.html, src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.ts, src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts, src/app/facility/analysis/analysis-banner/analysis-banner.component.css, src/app/facility/analysis/analysis-banner/analysis-banner.component.html, src/app/facility/analysis/analysis-banner/analysis-banner.component.ts, src/app/facility/analysis/analysis-footer/analysis-footer.component.css, src/app/facility/analysis/analysis-footer/analysis-footer.component.html, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.ts
=> Issue 1808: update analysis with dropdown to select other items

src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.css, src/app/account/account-analysis/account-analysis-banner/account-analysis-banner.component.html, src/app/account/account-analysis/account-analysis-footer/account-analysis-footer.component.html, src/app/facility/analysis/analysis-banner/analysis-banner.component.css, src/app/facility/analysis/analysis-banner/analysis-banner.component.html
=> add max height and scroll to analysis item dropdowns

package-lock.json, package.json
=> update example and bump version number

src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-form/predictors-data-form.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.html, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts, src/app/shared/helper-services/degree-days.service.ts, src/app/weather-data/annual-station-data/annual-station-data.component.ts, src/app/weather-data/monthly-station-data/monthly-station-data.component.html, src/app/weather-data/monthly-station-data/monthly-station-data.component.ts, src/app/weather-data/weather-data.component.ts, src/app/weather-data/weather-data.service.ts, src/app/weather-data/weather-stations/weather-stations.component.ts
=> bring back degree day service temporarily

src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.html, src/app/shared/helper-services/degree-days.service.ts
connects #1833 
connects #1822 
quick fix to logic flagging gaps in data
=> Issue 1833: Add bulk update button back in for weather data

src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.html, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.ts
=> Issue 1836: add note about manual override asterisk in predictor data

src/app/facility/utility-data/predictors/predictors-data/predictors-data-form/predictors-data-form.component.html, src/app/models/idbModels/predictorData.ts
=> Issue 1838: add notes field to predictor data entries

src/app/facility/utility-data/predictors/predictors-data/calculated-predictor-data-update/calculated-predictor-data-update.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-form/predictors-data-form.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.html, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts, src/app/shared/helper-services/degree-days.service.ts, src/app/weather-data/annual-station-data/annual-station-data.component.ts, src/app/weather-data/monthly-station-data/monthly-station-data.component.ts, src/app/weather-data/weather-data.component.ts, src/app/weather-data/weather-data.service.ts, src/app/weather-data/weather-stations/weather-stations.component.ts
=> Issue 1822: add weather server calls back in

package-lock.json, package.json
=> bump version number

src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-electricity-bill/edit-electricity-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts
=> Issue 1176: allow negative values for electricity consumption

src/app/account/account-home/account-home-summary/account-home-summary.component.html, src/app/models/idbModels/account.ts, src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.html, src/app/shared/settings-forms/sustainability-questions-form/sustainability-questions-form.component.ts
connects #1840 
connects #1826
=> Issue 1840: Add BP Partner Checkbox

src/app/facility/analysis/analysis.service.ts
=> Issue 1860: don't clear adjustment values when changing years

src/app/facility/utility-data/predictors/predictors-data/predictors-data-form/predictors-data-form.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.css, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.html, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/weather-station-modal/weather-station-modal.component.html, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/weather-station-modal/weather-station-modal.component.spec.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/weather-station-modal/weather-station-modal.component.ts, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts, src/app/facility/utility-data/predictors/predictors.module.ts, src/app/help-panel/weather-data-help/weather-stations-help/weather-stations-help.component.html, src/app/weather-data/annual-station-data/annual-station-data.component.ts, src/app/weather-data/weather-data.service.ts, src/app/weather-data/weather-stations/country-list.ts, src/app/weather-data/weather-stations/weather-stations-map/weather-stations-map.component.ts, src/app/weather-data/weather-stations/weather-stations.component.html, src/app/weather-data/weather-stations/weather-stations.component.ts
connects #1534 
connects #1619 
connects #1620 
connects #1621 
Adds location search for weather data.
Uses lat/long fetch from weather data API. 
Updates map to handle international weather stations
updates predictors page to use search with modal to select station.
=> Epic 1534: Weather search for international weather data

src/app/facility/utility-data/predictors/predictors-data/predictors-data-form/predictors-data-form.component.ts, src/app/facility/utility-data/predictors/predictors-data/predictors-data-table/predictors-data-table.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/weather-station-modal/weather-station-modal.component.html, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/weather-station-modal/weather-station-modal.component.ts, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts, src/app/shared/sharedHelperFuntions.ts, src/app/weather-data/weather-stations/weather-stations.component.html, src/app/weather-data/weather-stations/weather-stations.component.ts
=> Issue 1534: update facility search and lat/long decimals

src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.html, src/app/account/account-reports/account-report-setup/data-overview-setup/data-overview-setup.component.html, src/app/facility/analysis/run-analysis/analysis-setup/analysis-setup.component.html, src/app/facility/facility-reports/facility-report-setup/facility-overview-report-setup/facility-overview-report-setup.component.html, src/app/facility/visualization/correlation-plot-menu/correlation-plot-menu.component.html, src/app/shared/settings-forms/default-units-form/default-units-form.component.html
Changed the label 'Energy displayed as site or source?'
=> label changes in settings, reports, analysis and data visualization

package-lock.json, package.json
=> update version v0.13.3-beta

src/app/facility/utility-data/meter-grouping/meter-grouping.component.html
=> updated messaging for negative analysis groups

package-lock.json, package.json, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts
=> Issue 1876: Hotfix weather predictor creation

package-lock.json, package.json, src/app/facility/utility-data/meter-grouping/meter-grouping.component.html, src/app/facility/utility-data/predictors/predictors-management/edit-predictor-form/edit-predictor-form.component.ts, src/app/facility/utility-data/predictors/predictors-management/predictor-table/predictor-table.component.ts
=> Hotfix release VERIFI v0.13.4-beta

src/app/account/account-reports/account-reports.service.ts, src/app/account/account-settings/account-settings.component.ts
=> Issue 1888: fix to create facility bug

src/app/weather-data/annual-station-data/annual-station-table/annual-station-table.component.html, src/app/weather-data/annual-station-data/annual-station-table/annual-station-table.component.ts, src/app/weather-data/monthly-station-data/monthly-station-table/monthly-station-table.component.html, src/app/weather-data/monthly-station-data/monthly-station-table/monthly-station-table.component.ts
#1832 
Added copy table button to both monthly and daily weather data tables.
=> Issue 1832 - Added copy table button to weather data tables

src/app/shared/shared-analysis/calculations/regression-models.service.ts
#1872 
Regression model data validation message for report year corrected
=> Issue 1872 - Regression model data validation message for report year corrected

src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-bill.component.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-utility-bill/edit-utility-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/edit-bill/edit-vehicle-meter-bill/edit-vehicle-meter-bill.component.html, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data.service.ts, src/app/upload-data/data-setup/file-setup/confirm-and-submit/confirm-and-submit.component.ts, src/app/upload-data/data-setup/file-setup/confirm-readings/confirm-readings.component.ts
#1176 
Negative energy meters added to natural gas, other fuels and other energy
=> Issue 1176 - Negative energy meters added to natural gas, other fuels and other energy

src/app/shared/helper-services/backup-data.service.ts
#1890 
Changed date format in backup file naming
=> Issue 1890 - changed date format in backup file naming

src/app/calculations/emissions-calculations/emissions.ts, src/app/facility/utility-data/energy-consumption/utility-meter-data/utility-meter-data-table/electricity-data-table/electricity-data-table.component.ts
=> fix market emissions calcs

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/models/analysis.ts, src/app/shared/helper-services/backup-data.service.ts, src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> Issue 1872: added notes in the data validation column

src/app/facility/analysis/run-analysis/group-analysis/regression-model-selection/regression-model-selection.component.html, src/app/shared/shared-analysis/calculations/regression-models.service.ts
=> Issue 1872 - changed column title and the column text for data validation filter

src/app/account/account-analysis/account-analysis-setup/account-analysis-setup.component.ts
#1908 
facility analysis name changed for bulk analysis
=> Issue 1908 - facility analysis name changed for bulk analysis

package-lock.json, package.json
=> update version number v0.13.5-beta

src/app/calculations/emissions-calculations/emissions.ts, src/app/shared/helper-services/e-grid.service.ts, src/app/shared/settings-forms/default-units-form/e-grid-emissions-table/e-grid-emissions-table.component.html
=> Issue 1928: fix to calculations with direct emissions setting

package-lock.json, package.json
=> bump version number for release

src/app/core-components/manage-accounts/manage-accounts.component.html, src/app/core-components/manage-accounts/manage-accounts.component.ts
=> Issue 1509 - added new account button in account mgmt page

src/app/shared/data-overview/account-utility-usage-donut/account-utility-usage-donut.component.html, src/app/shared/data-overview/account-utility-usage-donut/account-utility-usage-donut.component.ts, src/app/shared/data-overview/account-water-usage-donut/account-water-usage-donut.component.html, src/app/shared/data-overview/account-water-usage-donut/account-water-usage-donut.component.ts, src/app/shared/data-overview/emissions-donut/emissions-donut.component.html, src/app/shared/data-overview/emissions-donut/emissions-donut.component.ts, src/app/shared/data-overview/facility-usage-donut/facility-usage-donut.component.html, src/app/shared/data-overview/facility-usage-donut/facility-usage-donut.component.ts, src/app/shared/data-overview/meter-usage-donut/meter-usage-donut.component.html, src/app/shared/data-overview/meter-usage-donut/meter-usage-donut.component.ts
#1853 
added treemap and bar chart to account and facility overview
=> Issue 1853 - added treemap and bar chart to account and facility overview

src/app/shared/label-with-tooltip/labelTooltips.ts, src/app/shared/settings-forms/general-information-form/general-information-form.component.css, src/app/shared/settings-forms/general-information-form/general-information-form.component.html, src/app/shared/settings-forms/general-information-form/general-information-form.component.ts, src/app/shared/settings-forms/general-information-form/general-information.service.spec.ts, src/app/shared/settings-forms/general-information-form/general-information.service.ts
=> Issue 1406 - address lookup to autofill state, city and zip

src/app/data-evaluation/account/account-reports/account-reports.service.ts, src/app/data-evaluation/account/account-reports/analysis-report/analysis-report.component.ts, src/app/data-evaluation/account/account-reports/better-climate-report/better-climate-report.component.ts, src/app/data-evaluation/account/account-reports/better-plants-report/better-plants-report.component.html, src/app/data-evaluation/account/account-reports/better-plants-report/better-plants-report.component.ts, src/app/data-evaluation/account/account-reports/data-overview-report/data-overview-account-report/account-section-report/account-section-report.component.ts, src/app/data-evaluation/account/account-reports/data-overview-report/data-overview-account-report/data-overview-account-report.component.ts, src/app/data-evaluation/account/account-reports/data-overview-report/data-overview-facility-report/data-overview-facility-report.component.ts, src/app/data-evaluation/account/account-reports/data-overview-report/data-overview-report.component.ts, src/app/data-evaluation/account/account-reports/performance-report/performance-report.component.ts, src/app/data-evaluation/account/account-reports/print-report-button/print-report-button.component.ts, src/app/data-evaluation/account/account.component.ts, src/app/data-evaluation/data-evaluation.component.html, src/app/data-evaluation/data-evaluation.component.ts, src/app/data-evaluation/data-evaluation.service.ts, src/app/data-evaluation/facility/facility-reports/facility-print-report-button/facility-print-report-button.component.ts, src/app/data-evaluation/facility/facility-reports/facility-reports.service.ts, src/app/data-evaluation/facility/facility-reports/report-results/facility-overview-report-results/facility-overview-report-results.component.ts, src/app/data-evaluation/facility/facility.component.ts, src/app/shared/data-overview/facility-section-report/facility-section-report.component.ts, src/app/shared/shared-reports/facility-analysis-report/annual-facility-analysis-report/annual-facility-analysis-report.component.ts, src/app/shared/shared-reports/facility-analysis-report/group-analysis-report/group-analysis-report.component.ts, src/app/shared/shared-reports/facility-analysis-report/group-analysis-report/group-annual-analysis-report/group-annual-analysis-report.component.ts, src/app/shared/shared-reports/facility-analysis-report/group-analysis-report/group-monthly-analysis-report/group-monthly-analysis-report.component.ts, src/app/shared/shared-reports/facility-analysis-report/monthly-facility-analysis-report/monthly-facility-analysis-report.component.ts
=> Epic 1525: fix printing for reports in new screens

src/app/shared/shared-data-quality-report-predictor/predictor-statistics-table/predictor-statistics-table.component.html, src/app/shared/shared-data-quality-report-predictor/predictor-timeseries-graph/predictor-timeseries-graph.component.ts, src/app/shared/shared-data-quality-report-predictor/predictorDataQualityStatistics.ts
=> Issue 1955 - changed outlier range. sorted data based on date.

src/app/data-management/data-management-home/data-management-home.component.html, src/app/data-management/data-management-side-panel/data-management-help-panel/data-management-facility-help/data-management-facility-help.component.ts, src/app/data-management/data-management-side-panel/data-management-help-panel/data-management-help-panel.component.ts, src/app/data-management/data-management-side-panel/data-management-side-panel.component.ts, src/app/data-management/data-management-side-panel/setup-checklist/setup-checklist.component.html, src/app/shared/shared-data-quality-report-meters/meter-statistics-table/meter-statistics-table.component.css, src/app/shared/shared-data-quality-report-predictor/predictor-statistics-table/predictor-statistics-table.component.css
connects #1987 
use components instead of name for dynamic help
default to todo list in panel
=> Issue 1987: default todo list in side panel and fixes to help text logic

src/app/indexedDB/update-db-entry.service.ts
=> set demand unit for meter

src/app/data-evaluation/help-panel/facility-help/facility-reports-help/facility-analysis-report-help/facility-analysis-report-help.component.html, src/app/data-evaluation/help-panel/facility-help/facility-reports-help/facility-emissions-factors-report-help/facility-emissions-factors-report-help.component.html, src/app/data-evaluation/help-panel/facility-help/facility-reports-help/facility-reports-help.component.html, src/app/data-evaluation/help-panel/facility-help/facility-reports-help/facility-reports-help.component.ts
=> updated help text

package-lock.json, src/app/core-components/home-page/home-page.component.css, src/app/core-components/home-page/home-page.component.html, src/app/core-components/home-page/home-page.component.ts, src/app/indexedDB/account-db.service.ts, src/app/indexedDB/db-changes.service.ts
connects #1956 
minor ui updates to the home screen
=> Epic 1956: version num update v0.14.0-beta

src/app/core-components/home-page/home-page.component.css, src/app/core-components/home-page/home-page.component.html
=> quickfix to styling

src/app/calculations/emissions-calculations/emissions.ts
=> Issue 2018: fixes to mobile total emissions for onsite transport

src/app/data-management/account-facilities/facility-data/facility-meters/facility-meter/facility-meter.component.ts, src/app/data-management/data-management-import/import-services/upload-data-v3.service.ts, src/app/data-management/data-management-import/shared-process-file/process-meters/process-meters.component.html, src/app/data-management/data-management-import/upload-files/upload-files.component.ts
connects #2015 
The "are you sure you want to navigate away?" warning was showing up when deleting a meter. Fixed the steps for that.
=> Issue 2015: Delete meter with changes to form

src/app/data-evaluation/account/account-analysis/account-analysis-footer/account-analysis-footer.component.css, src/app/data-evaluation/account/account-analysis/account-analysis-footer/account-analysis-footer.component.html, src/app/data-evaluation/account/account-analysis/account-analysis-footer/account-analysis-footer.component.ts, src/app/data-evaluation/data-evaluation.component.ts, src/app/data-evaluation/data-evaluation.service.ts, src/app/data-evaluation/facility/analysis/analysis-footer/analysis-footer.component.css, src/app/data-evaluation/facility/analysis/analysis-footer/analysis-footer.component.html, src/app/data-evaluation/facility/analysis/analysis-footer/analysis-footer.component.ts
connects #2024 
fixes broken navigation and floating buttons location
=> Issue 2024: fix button navigation for analysis

src/app/shared/data-overview/facility-usage-donut/facility-usage-donut.component.ts
=> Issue 2028 - fixed text issue in case of single facility in treemap

src/app/data-management/data-management-home/data-management-home.component.html, src/app/data-management/data-management-home/data-management-home.component.ts, src/app/data-management/data-management-home/update-weather-predictors-modal/update-weather-predictors-modal.component.css, src/app/data-management/data-management-home/update-weather-predictors-modal/update-weather-predictors-modal.component.html, src/app/data-management/data-management-home/update-weather-predictors-modal/update-weather-predictors-modal.component.spec.ts, src/app/data-management/data-management-home/update-weather-predictors-modal/update-weather-predictors-modal.component.ts, src/app/data-management/data-management.module.ts, src/app/weather-data/weather-data.service.ts, src/app/weather-data/weather-predictor-management.service.ts
connects #2033 
fixes bulk update of weather data from todo list
allows user to set date range of weather predictor data
=> Issue 2033: Bulk update weather data for entire account

src/environments/environment.dev-srv.ts, src/environments/environment.prod.ts
=> Issue 2041: update example and survey server url

package-lock.json, package.json
=> Epic 2016: update to v0.14.1-beta

src/app/calculations/performance-report-calculations/performanceReport.ts, src/app/data-evaluation/account/account-reports/performance-report/performance-report-facility-table/performance-report-facility-table.component.html, src/app/data-evaluation/account/account-reports/performance-report/performance-report-group-table/performance-report-group-table.component.html, src/app/data-evaluation/account/account-reports/performance-report/performance-report-utility-table/performance-report-utility-table.component.html, src/app/data-evaluation/account/account-reports/performance-report/performance-report-utility-table/performance-report-utility-table.component.ts
=> Issue 1980 - added change in savings to the performance report

package-lock.json, package.json
=> update version number for release (v0.14.3-beta)
